---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        ai_linalg["ai-linalg"]
        lib_ai_data_oak(["ai-data.oak"])
        ai_vec["ai-vec"]
        math_stats["math-stats"]
        sort["sort"]
        std["std"]
        math["math"]
        math_base["math-base"]
        math_geo["math-geo"]
    end
    thread --> std
    ai_linalg --> std
    ai_linalg --> thread
    lib_ai_data_oak --> std
    lib_ai_data_oak --> math
    lib_ai_data_oak --> ai_vec
    lib_ai_data_oak --> ai_linalg
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sort --> std
    sort --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    math_geo --> math_base