---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_data_oak(["ai-data.oak"])
    std("std")
    math("math")
    ai_vec("ai-vec")
    ai_linalg("ai-linalg")
    lib_ai_data_oak --> std
    lib_ai_data_oak --> math
    lib_ai_data_oak --> ai_vec
    lib_ai_data_oak --> ai_linalg