---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_decode_oak(["ai-decode.oak"])
    subgraph stdlib_ai ["ai"]
        ai_vec("ai-vec")
        ai_nn("ai-nn")
        ai_data("ai-data")
        ai_linalg("ai-linalg")
    end
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math_geo("math-geo")
        math_stats("math-stats")
        math("math")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        thread("thread")
        sort("sort")
    end
    thread --> std
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sort --> std
    sort --> thread
    ai_nn --> std
    ai_nn --> math
    ai_nn --> thread
    ai_nn --> ai_vec
    lib_ai_decode_oak --> std
    lib_ai_decode_oak --> sort
    lib_ai_decode_oak --> thread
    lib_ai_decode_oak --> ai_vec
    lib_ai_decode_oak --> ai_nn
    lib_ai_decode_oak --> ai_data
    math --> math_base
    math --> math_geo
    math --> math_stats
    ai_data --> std
    ai_data --> math
    ai_data --> ai_vec
    ai_data --> ai_linalg
    ai_linalg --> std
    ai_linalg --> thread