---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_decode_oak(["ai-decode.oak"])
    std("std")
    sort("sort")
    thread("thread")
    ai_vec("ai-vec")
    ai_nn("ai-nn")
    ai_data("ai-data")
    lib_ai_decode_oak --> std
    lib_ai_decode_oak --> sort
    lib_ai_decode_oak --> thread
    lib_ai_decode_oak --> ai_vec
    lib_ai_decode_oak --> ai_nn
    lib_ai_decode_oak --> ai_data