---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        math_stats["math-stats"]
        sort["sort"]
        ai_linalg["ai-linalg"]
        math_geo["math-geo"]
        math["math"]
        math_base["math-base"]
        ai_vec["ai-vec"]
        lib_ai_data_oak(["ai-data.oak"])
        std["std"]
    end
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sort --> std
    sort --> thread
    ai_linalg --> std
    ai_linalg --> thread
    math_geo --> math_base
    math --> math_base
    math --> math_geo
    math --> math_stats
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    lib_ai_data_oak --> std
    lib_ai_data_oak --> math
    lib_ai_data_oak --> ai_vec
    lib_ai_data_oak --> ai_linalg