---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_linalg_oak(["ai-linalg.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end
    thread --> std
    lib_ai_linalg_oak --> std
    lib_ai_linalg_oak --> thread