---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        math_geo["math-geo"]
        lib_ai_ml_oak(["ai-ml.oak"])
        std["std"]
        thread["thread"]
        sort["sort"]
        math_base["math-base"]
        math["math"]
        ai_vec["ai-vec"]
        math_stats["math-stats"]
    end
    math_geo --> math_base
    lib_ai_ml_oak --> std
    lib_ai_ml_oak --> sort
    lib_ai_ml_oak --> math
    lib_ai_ml_oak --> ai_vec
    thread --> std
    sort --> std
    sort --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread