---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_ml_oak(["ai-ml.oak"])
    math_geo --> math_base
    lib_ai_ml_oak --> std
    lib_ai_ml_oak --> sort
    lib_ai_ml_oak --> math
    lib_ai_ml_oak --> ai_vec
    sort --> std
    sort --> thread
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    subgraph stdlib_math ["math"]
        math_geo("math-geo")
        math_base("math-base")
        math_stats("math-stats")
        math("math")
    end
    subgraph stdlib_core ["Standard Library"]
        sort("sort")
        thread("thread")
        ai_vec("ai-vec")
        std("std")
    end