---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        sort["sort"]
        lib_ai_nn_oak(["ai-nn.oak"])
        math["math"]
        math_base["math-base"]
        math_geo["math-geo"]
        math_stats["math-stats"]
        ai_vec["ai-vec"]
        thread["thread"]
        std["std"]
    end
    sort --> std
    sort --> thread
    lib_ai_nn_oak --> std
    lib_ai_nn_oak --> math
    lib_ai_nn_oak --> thread
    lib_ai_nn_oak --> ai_vec
    math --> math_base
    math --> math_geo
    math --> math_stats
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    thread --> std