---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_nn_oak(["ai-nn.oak"])
    std("std")
    math("math")
    thread("thread")
    ai_vec("ai-vec")
    lib_ai_nn_oak --> std
    lib_ai_nn_oak --> math
    lib_ai_nn_oak --> thread
    lib_ai_nn_oak --> ai_vec