---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        math["math"]
        lib_ai_optim_oak(["ai-optim.oak"])
        std["std"]
        math_geo["math-geo"]
        ai_vec["ai-vec"]
        sort["sort"]
        math_base["math-base"]
        thread["thread"]
        math_stats["math-stats"]
    end
    math --> math_base
    math --> math_geo
    math --> math_stats
    lib_ai_optim_oak --> std
    lib_ai_optim_oak --> math
    lib_ai_optim_oak --> ai_vec
    math_geo --> math_base
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    sort --> std
    sort --> thread
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread