---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_optim_oak(["ai-optim.oak"])
    thread --> std
    sort --> std
    sort --> thread
    ai_vec --> std
    ai_vec --> math
    ai_vec --> thread
    lib_ai_optim_oak --> std
    lib_ai_optim_oak --> math
    lib_ai_optim_oak --> ai_vec
    math_geo --> math_base
    math --> math_base
    math --> math_geo
    math --> math_stats
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math_geo("math-geo")
        math("math")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        sort("sort")
        ai_vec("ai-vec")
        std("std")
    end