---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        str["str"]
        lib_ai_text_oak(["ai-text.oak"])
    end
    str --> std
    lib_ai_text_oak --> std
    lib_ai_text_oak --> str