---
title: Module Dependency Graph
---
flowchart LR
    lib_ai_oak(["ai.oak"])
    ai_data("ai-data")
    ai_text("ai-text")
    ai_ml("ai-ml")
    ai_decode("ai-decode")
    ai_vec("ai-vec")
    ai_linalg("ai-linalg")
    ai_nn("ai-nn")
    ai_optim("ai-optim")
    lib_ai_oak --> ai_vec
    lib_ai_oak --> ai_linalg
    lib_ai_oak --> ai_nn
    lib_ai_oak --> ai_optim
    lib_ai_oak --> ai_data
    lib_ai_oak --> ai_text
    lib_ai_oak --> ai_ml
    lib_ai_oak --> ai_decode