---
title: Module Dependency Graph
---
flowchart LR
    lib_assembler_oak(["assembler.oak"])
    subgraph stdlib_core ["Standard Library"]
        fmt("fmt")
        std("std")
        str("str")
    end
    fmt --> std
    lib_assembler_oak --> std
    lib_assembler_oak --> str
    lib_assembler_oak --> fmt
    str --> std