---
title: Module Dependency Graph
---
flowchart LR
    lib_ast_js_oak(["ast-js.oak"])
    std("std")
    str("str")
    fmt("fmt")
    lib_ast_js_oak --> std
    lib_ast_js_oak --> str
    lib_ast_js_oak --> fmt