---
title: Module Dependency Graph
---
flowchart LR
    lib_ast_java_oak(["ast-java.oak"])
    subgraph stdlib_core ["Standard Library"]
        str("str")
        fmt("fmt")
        std("std")
    end
    str --> std
    fmt --> std
    lib_ast_java_oak --> std
    lib_ast_java_oak --> str
    lib_ast_java_oak --> fmt