---
title: Module Dependency Graph
---
flowchart LR
    lib_ast_ts_oak(["ast-ts.oak"])
    str --> std
    fmt --> std
    ast_js --> std
    ast_js --> str
    ast_js --> fmt
    lib_ast_ts_oak --> std
    lib_ast_ts_oak --> str
    lib_ast_ts_oak --> fmt
    lib_ast_ts_oak --> ast_js
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        fmt("fmt")
        ast_js("ast-js")
    end