---
title: Module Dependency Graph
---
flowchart LR
    lib_ast_ts_oak(["ast-ts.oak"])
    std("std")
    str("str")
    fmt("fmt")
    ast_js("ast-js")
    lib_ast_ts_oak --> std
    lib_ast_ts_oak --> str
    lib_ast_ts_oak --> fmt
    lib_ast_ts_oak --> ast_js