---
title: Module Dependency Graph
---
flowchart LR
    lib_async_event_bus_oak(["async-event-bus.oak"])
    lib_async_event_bus_oak --> std
    subgraph stdlib_core ["Standard Library"]
        std("std")
    end