---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_wav_oak(["audio-wav.oak"])
    subgraph stdlib_core ["Standard Library"]
        str("str")
        thread("thread")
        std("std")
    end
    lib_audio_wav_oak --> std
    lib_audio_wav_oak --> str
    lib_audio_wav_oak --> thread
    str --> std
    thread --> std