---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_ogg_oak(["audio-ogg.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
    end
    lib_audio_ogg_oak --> std
    lib_audio_ogg_oak --> str
    lib_audio_ogg_oak --> thread
    str --> std
    thread --> std