---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_oak(["audio.oak"])
    subgraph stdlib_audio ["audio"]
        audio_wav("audio-wav")
        audio_fft("audio-fft")
        audio_aiff("audio-aiff")
        audio_au("audio-au")
        audio_ogg("audio-ogg")
        audio_raw("audio-raw")
        audio_complex("audio-complex")
        audio_dsp("audio-dsp")
    end
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math("math")
        math_geo("math-geo")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
        sort("sort")
    end
    math --> math_base
    math --> math_geo
    math --> math_stats
    sort --> std
    sort --> thread
    audio_wav --> std
    audio_wav --> str
    audio_wav --> thread
    thread --> std
    audio_fft --> std
    audio_fft --> math
    audio_fft --> audio_complex
    audio_fft --> thread
    audio_aiff --> std
    audio_aiff --> str
    audio_aiff --> math
    audio_aiff --> thread
    math_geo --> math_base
    lib_audio_oak --> std
    lib_audio_oak --> math
    lib_audio_oak --> audio_complex
    lib_audio_oak --> audio_fft
    lib_audio_oak --> audio_dsp
    lib_audio_oak --> audio_wav
    lib_audio_oak --> audio_aiff
    lib_audio_oak --> audio_au
    lib_audio_oak --> audio_raw
    lib_audio_oak --> audio_ogg
    lib_audio_oak --> thread
    str --> std
    audio_au --> std
    audio_au --> str
    audio_au --> thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    audio_ogg --> std
    audio_ogg --> str
    audio_ogg --> thread
    audio_raw --> std
    audio_raw --> str
    audio_raw --> thread
    audio_complex --> math
    audio_dsp --> std
    audio_dsp --> math
    audio_dsp --> thread