---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        str["str"]
        thread["thread"]
        lib_audio_wav_oak(["audio-wav.oak"])
    end
    str --> std
    thread --> std
    lib_audio_wav_oak --> std
    lib_audio_wav_oak --> str
    lib_audio_wav_oak --> thread