---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        math_stats["math-stats"]
        math_geo["math-geo"]
        audio_complex["audio-complex"]
        lib_audio_fft_oak(["audio-fft.oak"])
        math["math"]
        thread["thread"]
        math_base["math-base"]
        sort["sort"]
    end
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    math_geo --> math_base
    audio_complex --> math
    lib_audio_fft_oak --> std
    lib_audio_fft_oak --> math
    lib_audio_fft_oak --> audio_complex
    lib_audio_fft_oak --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    thread --> std
    sort --> std
    sort --> thread