---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        lib_audio_au_oak(["audio-au.oak"])
        std["std"]
        str["str"]
    end
    thread --> std
    lib_audio_au_oak --> std
    lib_audio_au_oak --> str
    lib_audio_au_oak --> thread
    str --> std