---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_raw_oak(["audio-raw.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
    end
    thread --> std
    lib_audio_raw_oak --> std
    lib_audio_raw_oak --> str
    lib_audio_raw_oak --> thread
    str --> std