---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_aiff_oak(["audio-aiff.oak"])
    subgraph stdlib_math ["math"]
        math_geo("math-geo")
        math("math")
        math_base("math-base")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
        sort("sort")
    end
    math_geo --> math_base
    math --> math_base
    math --> math_geo
    math --> math_stats
    str --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sort --> std
    sort --> thread
    thread --> std
    lib_audio_aiff_oak --> std
    lib_audio_aiff_oak --> str
    lib_audio_aiff_oak --> math
    lib_audio_aiff_oak --> thread