---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_ogg_oak(["audio-ogg.oak"])
    std("std")
    str("str")
    thread("thread")
    lib_audio_ogg_oak --> std
    lib_audio_ogg_oak --> str
    lib_audio_ogg_oak --> thread