---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_dsp_oak(["audio-dsp.oak"])
    lib_audio_dsp_oak --> std
    lib_audio_dsp_oak --> math
    lib_audio_dsp_oak --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sort --> std
    sort --> thread
    thread --> std
    subgraph stdlib_math ["math"]
        math("math")
        math_base("math-base")
        math_geo("math-geo")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        sort("sort")
        thread("thread")
    end