---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        std["std"]
        math_stats["math-stats"]
        math_base["math-base"]
        audio_au["audio-au"]
        audio_ogg["audio-ogg"]
        sort["sort"]
        math_geo["math-geo"]
        audio_raw["audio-raw"]
        audio_wav["audio-wav"]
        audio_complex["audio-complex"]
        audio_aiff["audio-aiff"]
        audio_fft["audio-fft"]
        str["str"]
        audio_dsp["audio-dsp"]
        lib_audio_oak(["audio.oak"])
        math["math"]
    end
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    audio_au --> std
    audio_au --> str
    audio_au --> thread
    audio_ogg --> std
    audio_ogg --> str
    audio_ogg --> thread
    sort --> std
    sort --> thread
    math_geo --> math_base
    audio_raw --> std
    audio_raw --> str
    audio_raw --> thread
    audio_wav --> std
    audio_wav --> str
    audio_wav --> thread
    audio_complex --> math
    audio_aiff --> std
    audio_aiff --> str
    audio_aiff --> math
    audio_aiff --> thread
    audio_fft --> std
    audio_fft --> math
    audio_fft --> audio_complex
    audio_fft --> thread
    str --> std
    audio_dsp --> std
    audio_dsp --> math
    audio_dsp --> thread
    lib_audio_oak --> std
    lib_audio_oak --> math
    lib_audio_oak --> audio_complex
    lib_audio_oak --> audio_fft
    lib_audio_oak --> audio_dsp
    lib_audio_oak --> audio_wav
    lib_audio_oak --> audio_aiff
    lib_audio_oak --> audio_au
    lib_audio_oak --> audio_raw
    lib_audio_oak --> audio_ogg
    lib_audio_oak --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats