---
title: Module Dependency Graph
---
flowchart LR
    lib_audio_wav_oak(["audio-wav.oak"])
    thread --> std
    lib_audio_wav_oak --> std
    lib_audio_wav_oak --> str
    lib_audio_wav_oak --> thread
    str --> std
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
    end