---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_b64_oak(["b64.oak"])
        std["std"]
        b64_hex["b64-hex"]
    end
    lib_b64_oak --> std
    lib_b64_oak --> b64_hex
    b64_hex --> std