---
title: Module Dependency Graph
---
flowchart LR
    lib_build_oak(["build.oak"])
    subgraph stdlib_syntax ["syntax"]
        syntax_macros("syntax-macros")
        syntax("syntax")
        syntax_print("syntax-print")
        syntax_tokenize("syntax-tokenize")
        syntax_parse("syntax-parse")
    end
    subgraph stdlib_wasm ["wasm"]
        wasm_vm("wasm-vm")
        wasm_vm_runtime("wasm-vm-runtime")
    end
    subgraph stdlib_math ["math"]
        math_stats("math-stats")
        math_base("math-base")
        math_geo("math-geo")
        math("math")
    end
    subgraph stdlib_pack ["pack"]
        pack("pack")
        pack_utils("pack-utils")
    end
    subgraph stdlib_Virtual ["Virtual"]
        Virtual_Bytecode("Virtual-Bytecode")
        Virtual("Virtual")
    end
    subgraph stdlib_runtime ["runtime"]
        runtime_codegen("runtime-codegen")
        runtime_js("runtime-js")
        runtime_native("runtime-native")
    end
    subgraph stdlib_build ["build"]
        build_config("build-config")
        build_render("build-render")
        build_ast("build-ast")
        build_render_node("build-render-node")
        build_analyze("build-analyze")
        build_includes("build-includes")
        build_imports("build-imports")
        build_ident("build-ident")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        json("json")
        sort("sort")
        fmt("fmt")
        fs("fs")
        path("path")
        ast_transform("ast-transform")
        transpile("transpile")
        bundle_utils("bundle-utils")
        thread("thread")
        shell("shell")
        str("str")
    end
    fs --> thread
    syntax_macros --> std
    syntax_macros --> syntax_parse
    build_config --> std
    build_config --> build_includes
    Virtual_Bytecode --> std
    Virtual_Bytecode --> syntax
    Virtual_Bytecode --> wasm_vm
    Virtual_Bytecode --> fmt
    Virtual_Bytecode --> str
    runtime_codegen --> runtime_native
    runtime_codegen --> runtime_js
    runtime_codegen --> wasm_vm
    runtime_codegen --> wasm_vm_runtime
    runtime_codegen --> std
    runtime_codegen --> str
    shell --> std
    shell --> str
    shell --> fmt
    shell --> path
    shell --> fs
    path --> std
    path --> str
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    pack --> std
    pack --> fmt
    pack --> fs
    pack --> str
    pack --> path
    pack --> Virtual
    pack --> shell
    pack --> pack_utils
    pack --> transpile
    pack_utils --> std
    pack_utils --> str
    pack_utils --> json
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    thread --> std
    ast_transform --> std
    transpile --> std
    transpile --> fmt
    transpile --> ast_transform
    str --> std
    bundle_utils --> std
    build_render --> std
    build_render --> str
    build_render --> sort
    build_render --> fmt
    build_render --> build_render_node
    json --> std
    json --> str
    build_ast --> std
    build_ast --> sort
    build_ast --> path
    build_ast --> bundle_utils
    build_ast --> build_includes
    math_geo --> math_base
    build_render_node --> std
    build_render_node --> str
    build_render_node --> sort
    build_render_node --> fmt
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    math --> math_base
    math --> math_geo
    math --> math_stats
    Virtual --> std
    Virtual --> syntax
    Virtual --> str
    Virtual --> fmt
    Virtual --> fs
    Virtual --> Virtual_Bytecode
    sort --> std
    sort --> thread
    build_analyze --> std
    build_includes --> std
    build_includes --> str
    build_includes --> path
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    build_imports --> std
    build_imports --> build_includes
    wasm_vm_runtime --> std
    wasm_vm_runtime --> str
    wasm_vm_runtime --> fmt
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    lib_build_oak --> std
    lib_build_oak --> str
    lib_build_oak --> sort
    lib_build_oak --> fs
    lib_build_oak --> fmt
    lib_build_oak --> path
    lib_build_oak --> json
    lib_build_oak --> syntax
    lib_build_oak --> bundle_utils
    lib_build_oak --> ast_transform
    lib_build_oak --> transpile
    lib_build_oak --> pack
    lib_build_oak --> build_includes
    lib_build_oak --> build_ident
    lib_build_oak --> build_ast
    lib_build_oak --> build_analyze
    lib_build_oak --> build_render
    lib_build_oak --> build_config
    lib_build_oak --> build_imports
    lib_build_oak --> thread
    lib_build_oak --> runtime_codegen
    fmt --> std
    build_ident --> std
    build_ident --> str