---
title: Module Dependency Graph
---
flowchart LR
    lib_build_includes_oak(["build-includes.oak"])
    lib_build_includes_oak --> std
    lib_build_includes_oak --> str
    lib_build_includes_oak --> path
    str --> std
    path --> std
    path --> str
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        path("path")
    end