---
title: Module Dependency Graph
---
flowchart LR
    lib_build_ast_oak(["build-ast.oak"])
    subgraph stdlib_core ["Standard Library"]
        bundle_utils("bundle-utils")
        build_includes("build-includes")
        std("std")
        sort("sort")
        thread("thread")
        path("path")
        str("str")
    end
    str --> std
    bundle_utils --> std
    build_includes --> std
    build_includes --> str
    build_includes --> path
    lib_build_ast_oak --> std
    lib_build_ast_oak --> sort
    lib_build_ast_oak --> path
    lib_build_ast_oak --> bundle_utils
    lib_build_ast_oak --> build_includes
    sort --> std
    sort --> thread
    thread --> std
    path --> std
    path --> str