---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_build_analyze_oak(["build-analyze.oak"])
        std["std"]
    end
    lib_build_analyze_oak --> std