---
title: Module Dependency Graph
---
flowchart LR
    lib_build_ast_oak(["build-ast.oak"])
    bundle_utils("bundle-utils")
    build_includes("build-includes")
    std("std")
    sort("sort")
    path("path")
    lib_build_ast_oak --> std
    lib_build_ast_oak --> sort
    lib_build_ast_oak --> path
    lib_build_ast_oak --> bundle_utils
    lib_build_ast_oak --> build_includes