---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        str["str"]
        build_config["build-config"]
        pack_utils["pack-utils"]
        math["math"]
        path["path"]
        build_analyze["build-analyze"]
        syntax["syntax"]
        thread["thread"]
        math_stats["math-stats"]
        ast_transform["ast-transform"]
        bundle_utils["bundle-utils"]
        build_imports["build-imports"]
        build_includes["build-includes"]
        build_ast["build-ast"]
        json["json"]
        build_ident["build-ident"]
        fmt["fmt"]
        build_render["build-render"]
        sort["sort"]
        build_render_node["build-render-node"]
        std["std"]
        syntax_macros["syntax-macros"]
        lib_build_oak(["build.oak"])
        transpile["transpile"]
        syntax_parse["syntax-parse"]
        math_base["math-base"]
        shell["shell"]
        Virtual_Bytecode["Virtual-Bytecode"]
        pack["pack"]
        Virtual["Virtual"]
        fs["fs"]
        runtime_codegen["runtime-codegen"]
        wasm_vm["wasm-vm"]
        runtime_native["runtime-native"]
        runtime_js["runtime-js"]
        wasm_vm_runtime["wasm-vm-runtime"]
        syntax_tokenize["syntax-tokenize"]
        math_geo["math-geo"]
        syntax_print["syntax-print"]
    end
    str --> std
    build_config --> std
    build_config --> build_includes
    pack_utils --> std
    pack_utils --> str
    pack_utils --> json
    math --> math_base
    math --> math_geo
    math --> math_stats
    path --> std
    path --> str
    build_analyze --> std
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    ast_transform --> std
    bundle_utils --> std
    build_imports --> std
    build_imports --> build_includes
    build_includes --> std
    build_includes --> str
    build_includes --> path
    build_ast --> std
    build_ast --> sort
    build_ast --> path
    build_ast --> bundle_utils
    build_ast --> build_includes
    json --> std
    json --> str
    build_ident --> std
    build_ident --> str
    fmt --> std
    build_render --> std
    build_render --> str
    build_render --> sort
    build_render --> fmt
    build_render --> build_render_node
    sort --> std
    sort --> thread
    build_render_node --> std
    build_render_node --> str
    build_render_node --> sort
    build_render_node --> fmt
    syntax_macros --> std
    syntax_macros --> syntax_parse
    lib_build_oak --> std
    lib_build_oak --> str
    lib_build_oak --> sort
    lib_build_oak --> fs
    lib_build_oak --> fmt
    lib_build_oak --> path
    lib_build_oak --> json
    lib_build_oak --> syntax
    lib_build_oak --> bundle_utils
    lib_build_oak --> ast_transform
    lib_build_oak --> transpile
    lib_build_oak --> pack
    lib_build_oak --> build_includes
    lib_build_oak --> build_ident
    lib_build_oak --> build_ast
    lib_build_oak --> build_analyze
    lib_build_oak --> build_render
    lib_build_oak --> build_config
    lib_build_oak --> build_imports
    lib_build_oak --> thread
    lib_build_oak --> runtime_codegen
    transpile --> std
    transpile --> fmt
    transpile --> ast_transform
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    shell --> std
    shell --> str
    shell --> fmt
    shell --> path
    shell --> fs
    Virtual_Bytecode --> std
    Virtual_Bytecode --> syntax
    Virtual_Bytecode --> wasm_vm
    Virtual_Bytecode --> fmt
    Virtual_Bytecode --> str
    pack --> std
    pack --> fmt
    pack --> fs
    pack --> str
    pack --> path
    pack --> Virtual
    pack --> shell
    pack --> pack_utils
    pack --> transpile
    Virtual --> std
    Virtual --> syntax
    Virtual --> str
    Virtual --> fmt
    Virtual --> fs
    Virtual --> Virtual_Bytecode
    fs --> thread
    runtime_codegen --> runtime_native
    runtime_codegen --> runtime_js
    runtime_codegen --> wasm_vm
    runtime_codegen --> wasm_vm_runtime
    runtime_codegen --> std
    runtime_codegen --> str
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    wasm_vm_runtime --> std
    wasm_vm_runtime --> str
    wasm_vm_runtime --> fmt
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    math_geo --> math_base
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize