---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_build_render_node_oak(["build-render-node.oak"])
        std["std"]
        str["str"]
        sort["sort"]
        thread["thread"]
        fmt["fmt"]
    end
    lib_build_render_node_oak --> std
    lib_build_render_node_oak --> str
    lib_build_render_node_oak --> sort
    lib_build_render_node_oak --> fmt
    str --> std
    sort --> std
    sort --> thread
    thread --> std
    fmt --> std