---
title: Module Dependency Graph
---
flowchart LR
    lib_bundle_utils_oak(["bundle-utils.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
    end
    lib_bundle_utils_oak --> std