---
title: Module Dependency Graph
---
flowchart LR
    lib_bundle_ast_oak(["bundle-ast.oak"])
    ast_transform("ast-transform")
    std("std")
    str("str")
    lib_bundle_ast_oak --> std
    lib_bundle_ast_oak --> str
    lib_bundle_ast_oak --> ast_transform