---
title: Module Dependency Graph
---
flowchart LR
    lib_bundle_ast_oak(["bundle-ast.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        ast_transform("ast-transform")
    end
    str --> std
    ast_transform --> std
    lib_bundle_ast_oak --> std
    lib_bundle_ast_oak --> str
    lib_bundle_ast_oak --> ast_transform