---
title: Module Dependency Graph
---
flowchart LR
    lib_cli_oak(["cli.oak"])
    lib_cli_oak --> std
    lib_cli_oak --> str
    str --> std
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end