---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        str["str"]
        lib_cli_oak(["cli.oak"])
        std["std"]
    end
    str --> std
    lib_cli_oak --> std
    lib_cli_oak --> str