---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        str["str"]
        std["std"]
        fmt["fmt"]
        lib_codegen_go_oak(["codegen-go.oak"])
    end
    str --> std
    fmt --> std
    lib_codegen_go_oak --> std
    lib_codegen_go_oak --> str
    lib_codegen_go_oak --> fmt