---
title: Module Dependency Graph
---
flowchart LR
    lib_codegen_common_oak(["codegen-common.oak"])
    std("std")
    str("str")
    fmt("fmt")
    lib_codegen_common_oak --> std
    lib_codegen_common_oak --> str
    lib_codegen_common_oak --> fmt