---
title: Module Dependency Graph
---
flowchart LR
    lib_codecols_oak(["codecols.oak"])
    std("std")
    str("str")
    sort("sort")
    math("math")
    thread("thread")
    lib_codecols_oak --> std
    lib_codecols_oak --> str
    lib_codecols_oak --> sort
    lib_codecols_oak --> math
    lib_codecols_oak --> thread