---
title: Module Dependency Graph
---
flowchart LR
    lib_codecols_oak(["codecols.oak"])
    subgraph stdlib_math ["math"]
        math_geo("math-geo")
        math("math")
        math_base("math-base")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        sort("sort")
        str("str")
        thread("thread")
    end
    math_geo --> math_base
    sort --> std
    sort --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    lib_codecols_oak --> std
    lib_codecols_oak --> str
    lib_codecols_oak --> sort
    lib_codecols_oak --> math
    lib_codecols_oak --> thread
    str --> std
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread