---
title: Module Dependency Graph
---
flowchart LR
    lib_codegen_go_oak(["codegen-go.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        fmt("fmt")
    end
    fmt --> std
    lib_codegen_go_oak --> std
    lib_codegen_go_oak --> str
    lib_codegen_go_oak --> fmt
    str --> std