---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_codegen_native_oak(["codegen-native.oak"])
        std["std"]
        str["str"]
        fmt["fmt"]
    end
    lib_codegen_native_oak --> std
    lib_codegen_native_oak --> str
    lib_codegen_native_oak --> fmt
    str --> std
    fmt --> std