---
title: Module Dependency Graph
---
flowchart LR
    lib_compression_rle_oak(["compression-rle.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end
    str --> std
    lib_compression_rle_oak --> std
    lib_compression_rle_oak --> str