---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        sort["sort"]
        std["std"]
        thread["thread"]
        lib_compression_huffman_oak(["compression-huffman.oak"])
        str["str"]
    end
    sort --> std
    sort --> thread
    thread --> std
    lib_compression_huffman_oak --> std
    lib_compression_huffman_oak --> str
    lib_compression_huffman_oak --> sort
    str --> std