---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        str["str"]
        lib_compression_rle_oak(["compression-rle.oak"])
    end
    str --> std
    lib_compression_rle_oak --> std
    lib_compression_rle_oak --> str