---
title: Module Dependency Graph
---
flowchart LR
    lib_compression_huffman_oak(["compression-huffman.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
        sort("sort")
    end
    str --> std
    sort --> std
    sort --> thread
    thread --> std
    lib_compression_huffman_oak --> std
    lib_compression_huffman_oak --> str
    lib_compression_huffman_oak --> sort