---
title: Module Dependency Graph
---
flowchart LR
    lib_compression_lzw_oak(["compression-lzw.oak"])
    std("std")
    str("str")
    lib_compression_lzw_oak --> std
    lib_compression_lzw_oak --> str