---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        sort["sort"]
        thread["thread"]
        compression_lzw["compression-lzw"]
        lib_compression_oak(["compression.oak"])
        compression_rle["compression-rle"]
        str["str"]
        std["std"]
        compression_huffman["compression-huffman"]
    end
    sort --> std
    sort --> thread
    thread --> std
    compression_lzw --> std
    compression_lzw --> str
    lib_compression_oak --> std
    lib_compression_oak --> thread
    lib_compression_oak --> compression_rle
    lib_compression_oak --> compression_huffman
    lib_compression_oak --> compression_lzw
    compression_rle --> std
    compression_rle --> str
    str --> std
    compression_huffman --> std
    compression_huffman --> str
    compression_huffman --> sort