---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        str["str"]
        thread["thread"]
        lib_crypto_oak(["crypto.oak"])
    end
    str --> std
    thread --> std
    lib_crypto_oak --> std
    lib_crypto_oak --> str
    lib_crypto_oak --> thread