---
title: Module Dependency Graph
---
flowchart LR
    lib_dataprot_oak(["dataprot.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        thread("thread")
    end
    lib_dataprot_oak --> std
    lib_dataprot_oak --> thread
    thread --> std