---
title: Module Dependency Graph
---
flowchart LR
    lib_data_xml_oak(["data-xml.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end
    lib_data_xml_oak --> std
    lib_data_xml_oak --> str
    str --> std