---
title: Module Dependency Graph
---
flowchart LR
    lib_data_csv_oak(["data-csv.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end
    str --> std
    lib_data_csv_oak --> std
    lib_data_csv_oak --> str