---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        data_ini["data-ini"]
        msgpack["msgpack"]
        data_xml["data-xml"]
        lib_data_oak(["data.oak"])
        thread["thread"]
        fmt["fmt"]
        fs["fs"]
        data_yaml["data-yaml"]
        json["json"]
        md["md"]
        data_csv["data-csv"]
        http["http"]
        str["str"]
        sort["sort"]
        data_toml["data-toml"]
    end
    data_ini --> std
    data_ini --> str
    msgpack --> std
    msgpack --> str
    msgpack --> thread
    data_xml --> std
    data_xml --> str
    lib_data_oak --> data_csv
    lib_data_oak --> json
    lib_data_oak --> data_toml
    lib_data_oak --> data_xml
    lib_data_oak --> data_ini
    lib_data_oak --> data_yaml
    lib_data_oak --> md
    lib_data_oak --> msgpack
    thread --> std
    fmt --> std
    fs --> thread
    data_yaml --> std
    data_yaml --> str
    json --> std
    json --> str
    md --> std
    md --> str
    md --> fmt
    md --> http
    data_csv --> std
    data_csv --> str
    http --> std
    http --> str
    http --> fs
    http --> fmt
    http --> sort
    http --> json
    http --> thread
    str --> std
    sort --> std
    sort --> thread
    data_toml --> std
    data_toml --> str