---
title: Module Dependency Graph
---
flowchart LR
    lib_data_yaml_oak(["data-yaml.oak"])
    lib_data_yaml_oak --> std
    lib_data_yaml_oak --> str
    str --> std
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end