---
title: Module Dependency Graph
---
flowchart LR
    lib_dataprot_oak(["dataprot.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end
    thread --> std
    lib_dataprot_oak --> std
    lib_dataprot_oak --> thread