---
title: Module Dependency Graph
---
flowchart LR
    lib_data_toml_oak(["data-toml.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end
    lib_data_toml_oak --> std
    lib_data_toml_oak --> str
    str --> std