---
title: Module Dependency Graph
---
flowchart LR
    lib_data_ini_oak(["data-ini.oak"])
    str --> std
    lib_data_ini_oak --> std
    lib_data_ini_oak --> str
    subgraph stdlib_core ["Standard Library"]
        str("str")
        std("std")
    end