---
title: Module Dependency Graph
---
flowchart LR
    lib_data_oak(["data.oak"])
    subgraph stdlib_data ["data"]
        data_toml("data-toml")
        data_csv("data-csv")
        data_xml("data-xml")
        data_yaml("data-yaml")
        data_ini("data-ini")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        md("md")
        msgpack("msgpack")
        sort("sort")
        fmt("fmt")
        fs("fs")
        str("str")
        http("http")
        std("std")
        json("json")
    end
    fs --> thread
    md --> std
    md --> str
    md --> fmt
    md --> http
    msgpack --> std
    msgpack --> str
    msgpack --> thread
    lib_data_oak --> data_csv
    lib_data_oak --> json
    lib_data_oak --> data_toml
    lib_data_oak --> data_xml
    lib_data_oak --> data_ini
    lib_data_oak --> data_yaml
    lib_data_oak --> md
    lib_data_oak --> msgpack
    data_toml --> std
    data_toml --> str
    str --> std
    http --> std
    http --> str
    http --> fs
    http --> fmt
    http --> sort
    http --> json
    http --> thread
    sort --> std
    sort --> thread
    json --> std
    json --> str
    data_csv --> std
    data_csv --> str
    data_xml --> std
    data_xml --> str
    data_yaml --> std
    data_yaml --> str
    data_ini --> std
    data_ini --> str
    thread --> std
    fmt --> std