---
title: Module Dependency Graph
---
flowchart LR
    lib_datetime_oak(["datetime.oak"])
    subgraph stdlib_math ["math"]
        math_stats("math-stats")
        math("math")
        math_base("math-base")
        math_geo("math-geo")
    end
    subgraph stdlib_core ["Standard Library"]
        sort("sort")
        thread("thread")
        str("str")
        std("std")
        fmt("fmt")
    end
    thread --> std
    str --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    fmt --> std
    lib_datetime_oak --> std
    lib_datetime_oak --> str
    lib_datetime_oak --> math
    lib_datetime_oak --> fmt
    sort --> std
    sort --> thread
    math_geo --> math_base