---
title: Module Dependency Graph
---
flowchart LR
    lib_debug_oak(["debug.oak"])
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math_geo("math-geo")
        math_stats("math-stats")
        math("math")
    end
    subgraph stdlib_core ["Standard Library"]
        str("str")
        thread("thread")
        std("std")
        sort("sort")
        fmt("fmt")
    end
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    lib_debug_oak --> std
    lib_debug_oak --> str
    lib_debug_oak --> math
    lib_debug_oak --> sort
    lib_debug_oak --> fmt
    math --> math_base
    math --> math_geo
    math --> math_stats
    sort --> std
    sort --> thread
    fmt --> std
    str --> std
    thread --> std