---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        math_geo["math-geo"]
        math_stats["math-stats"]
        std["std"]
        fmt["fmt"]
        lib_debug_oak(["debug.oak"])
        thread["thread"]
        sort["sort"]
        math_base["math-base"]
        str["str"]
        math["math"]
    end
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    fmt --> std
    lib_debug_oak --> std
    lib_debug_oak --> str
    lib_debug_oak --> math
    lib_debug_oak --> sort
    lib_debug_oak --> fmt
    thread --> std
    sort --> std
    sort --> thread
    str --> std
    math --> math_base
    math --> math_geo
    math --> math_stats