---
title: Module Dependency Graph
---
flowchart LR
    lib_email_imap_oak(["email-imap.oak"])
    std("std")
    str("str")
    thread("thread")
    socket("socket")
    lib_email_imap_oak --> std
    lib_email_imap_oak --> str
    lib_email_imap_oak --> thread
    lib_email_imap_oak --> socket