---
title: Module Dependency Graph
---
flowchart LR
    lib_email_smtp_oak(["email-smtp.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        socket("socket")
        std("std")
        str("str")
    end
    thread --> std
    lib_email_smtp_oak --> std
    lib_email_smtp_oak --> str
    lib_email_smtp_oak --> thread
    lib_email_smtp_oak --> socket
    str --> std