---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        socket["socket"]
        lib_email_smtp_oak(["email-smtp.oak"])
        std["std"]
        str["str"]
        thread["thread"]
    end
    lib_email_smtp_oak --> std
    lib_email_smtp_oak --> str
    lib_email_smtp_oak --> thread
    lib_email_smtp_oak --> socket
    str --> std
    thread --> std