---
title: Module Dependency Graph
---
flowchart LR
    lib_email_oak(["email.oak"])
    email_smtp("email-smtp")
    email_pop("email-pop")
    email_imap("email-imap")
    lib_email_oak --> email_smtp
    lib_email_oak --> email_pop
    lib_email_oak --> email_imap