---
title: Module Dependency Graph
---
flowchart LR
    lib_email_pop_oak(["email-pop.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        socket("socket")
        std("std")
        str("str")
    end
    thread --> std
    lib_email_pop_oak --> std
    lib_email_pop_oak --> str
    lib_email_pop_oak --> thread
    lib_email_pop_oak --> socket
    str --> std