---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_email_pop_oak(["email-pop.oak"])
        std["std"]
        str["str"]
        thread["thread"]
        socket["socket"]
    end
    lib_email_pop_oak --> std
    lib_email_pop_oak --> str
    lib_email_pop_oak --> thread
    lib_email_pop_oak --> socket
    str --> std
    thread --> std