---
title: Module Dependency Graph
---
flowchart LR
    lib_fs_oak(["fs.oak"])
    lib_fs_oak --> thread
    thread --> std
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end