---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_fs_oak(["fs.oak"])
        thread["thread"]
        std["std"]
    end
    lib_fs_oak --> thread
    thread --> std