---
title: Module Dependency Graph
---
flowchart LR
    lib_gpus_oak(["gpus.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        gpu("gpu")
    end
    lib_gpus_oak --> std
    lib_gpus_oak --> gpu
    gpu --> std