---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_shader_noise_oak(["gui-shader-noise.oak"])
    subgraph stdlib_core ["Standard Library"]
        gui_shader_math("gui-shader-math")
        thread("thread")
        std("std")
    end
    lib_gui_shader_noise_oak --> gui_shader_math
    lib_gui_shader_noise_oak --> thread
    gui_shader_math --> thread
    thread --> std