---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_loop_oak(["gui-loop.oak"])
    windows("windows")
    gui_events("gui-events")
    gui_native_linux("gui-native-linux")
    gui_common("gui-common")
    gui_thread("gui-thread")
    lib_gui_loop_oak --> windows
    lib_gui_loop_oak --> gui_events
    lib_gui_loop_oak --> gui_native_linux
    lib_gui_loop_oak --> gui_common
    lib_gui_loop_oak --> gui_thread