---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        math_base["math-base"]
        windows_loader["windows-loader"]
        windows_net["windows-net"]
        gui_draw["gui-draw"]
        windows_windowing["windows-windowing"]
        std["std"]
        gui_shader_codegen["gui-shader-codegen"]
        gui_shader_color["gui-shader-color"]
        gui_shader["gui-shader"]
        math_stats["math-stats"]
        linux_constants["linux-constants"]
        lib_gui_video_oak(["gui-video.oak"])
        windows["windows"]
        linux_loader["linux-loader"]
        windows_gdi["windows-gdi"]
        linux_core["linux-core"]
        sys["sys"]
        gui_shader_sdf["gui-shader-sdf"]
        math["math"]
        windows_registry["windows-registry"]
        sort["sort"]
        gui_thread["gui-thread"]
        linux["linux"]
        windows_constants["windows-constants"]
        gui_shader_noise["gui-shader-noise"]
        linux_windowing["linux-windowing"]
        linux_libc["linux-libc"]
        writes["writes"]
        math_geo["math-geo"]
        gui_shader_math["gui-shader-math"]
        thread["thread"]
        gui_common["gui-common"]
        gui_fonts["gui-fonts"]
        windows_core["windows-core"]
        windows_kernel["windows-kernel"]
        gui_color["gui-color"]
        windows_flags["windows-flags"]
        video["video"]
    end
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_draw --> std
    gui_draw --> windows
    gui_draw --> linux
    gui_draw --> gui_common
    gui_draw --> gui_fonts
    gui_draw --> writes
    gui_draw --> gui_thread
    gui_draw --> thread
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    gui_shader_codegen --> std
    gui_shader_codegen --> thread
    gui_shader_color --> gui_color
    gui_shader_color --> gui_shader_math
    gui_shader_color --> thread
    gui_shader --> std
    gui_shader --> gui_draw
    gui_shader --> thread
    gui_shader --> gui_shader_math
    gui_shader --> gui_shader_color
    gui_shader --> gui_shader_noise
    gui_shader --> gui_shader_sdf
    gui_shader --> gui_shader_codegen
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    lib_gui_video_oak --> std
    lib_gui_video_oak --> video
    lib_gui_video_oak --> gui_color
    lib_gui_video_oak --> gui_shader
    lib_gui_video_oak --> thread
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    linux_core --> sys
    linux_core --> linux_constants
    sys --> std
    gui_shader_sdf --> gui_shader_math
    gui_shader_sdf --> gui_shader_color
    gui_shader_sdf --> gui_shader_noise
    gui_shader_sdf --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    sort --> std
    sort --> thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    gui_shader_noise --> gui_shader_math
    gui_shader_noise --> thread
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    math_geo --> math_base
    gui_shader_math --> thread
    thread --> std
    gui_fonts --> gui_common
    gui_fonts --> gui_thread
    windows_core --> sys
    windows_core --> windows_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    video --> std
    video --> math
    video --> thread