---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_oak(["gui-native-win-vulkan.oak"])
    gui_thread("gui-thread")
    gui_native_win_vulkan_init("gui-native-win-vulkan-init")
    gui_native_win_vulkan_swapchain("gui-native-win-vulkan-swapchain")
    gui_native_win_vulkan_present("gui-native-win-vulkan-present")
    lib_gui_native_win_vulkan_oak --> gui_thread
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_init
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_swapchain
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_present