---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_close_oak(["gui-native-win-close.oak"])
    windows("windows")
    gui_thread("gui-thread")
    lib_gui_native_win_close_oak --> windows
    lib_gui_native_win_close_oak --> gui_thread