---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_linux_oak(["gui-native-linux.oak"])
    gui_common("gui-common")
    gui_thread("gui-thread")
    linux("linux")
    lib_gui_native_linux_oak --> linux
    lib_gui_native_linux_oak --> gui_common
    lib_gui_native_linux_oak --> gui_thread