---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_close_oak(["gui-native-win-close.oak"])
    subgraph stdlib_gui ["gui"]
        gui_thread("gui-thread")
        gui_common("gui-common")
    end
    subgraph stdlib_windows ["windows"]
        windows("windows")
        windows_net("windows-net")
        windows_flags("windows-flags")
        windows_gdi("windows-gdi")
        windows_loader("windows-loader")
        windows_windowing("windows-windowing")
        windows_registry("windows-registry")
        windows_core("windows-core")
        windows_kernel("windows-kernel")
        windows_constants("windows-constants")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        writes("writes")
        thread("thread")
        std("std")
    end
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    sys --> std
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    windows_core --> sys
    windows_core --> windows_constants
    thread --> std
    lib_gui_native_win_close_oak --> windows
    lib_gui_native_win_close_oak --> gui_thread
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags