---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_poll_oak(["gui-native-win-poll.oak"])
    windows("windows")
    gui_thread("gui-thread")
    lib_gui_native_win_poll_oak --> windows
    lib_gui_native_win_poll_oak --> gui_thread