---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_audio_oak(["gui-audio.oak"])
    subgraph stdlib_math ["math"]
        math("math")
        math_geo("math-geo")
        math_base("math-base")
        math_stats("math-stats")
    end
    subgraph stdlib_gui ["gui"]
        gui_thread("gui-thread")
        gui_common("gui-common")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        sort("sort")
        std("std")
    end
    thread --> std
    math --> math_base
    math --> math_geo
    math --> math_stats
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    math_geo --> math_base
    sort --> std
    sort --> thread
    lib_gui_audio_oak --> std
    lib_gui_audio_oak --> math
    lib_gui_audio_oak --> gui_thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread