---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_mesh_oak(["gui-mesh.oak"])
    subgraph stdlib_core ["Standard Library"]
        gui_common("gui-common")
        thread("thread")
        std("std")
    end
    lib_gui_mesh_oak --> gui_common
    lib_gui_mesh_oak --> thread
    thread --> std