---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_gamepad_oak(["gui-gamepad.oak"])
    sys("sys")
    windows("windows")
    gui_thread("gui-thread")
    writes("writes")
    lib_gui_gamepad_oak --> sys
    lib_gui_gamepad_oak --> windows
    lib_gui_gamepad_oak --> gui_thread
    lib_gui_gamepad_oak --> writes