---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        gui_3dmath["gui-3dmath"]
        gui_thread["gui-thread"]
        std["std"]
        thread["thread"]
        gui_common["gui-common"]
        lib_gui_raster_oak(["gui-raster.oak"])
        gui_lighting["gui-lighting"]
    end
    gui_3dmath --> gui_common
    gui_3dmath --> thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    thread --> std
    lib_gui_raster_oak --> gui_common
    lib_gui_raster_oak --> gui_lighting
    lib_gui_raster_oak --> gui_3dmath
    lib_gui_raster_oak --> gui_thread
    lib_gui_raster_oak --> thread
    gui_lighting --> gui_common
    gui_lighting --> thread