---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_ddraw_oak(["gui-native-win-ddraw.oak"])
    gui_thread("gui-thread")
    win_common("win-common")
    windows("windows")
    gui_common("gui-common")
    lib_gui_native_win_ddraw_oak --> windows
    lib_gui_native_win_ddraw_oak --> gui_common
    lib_gui_native_win_ddraw_oak --> gui_thread
    lib_gui_native_win_ddraw_oak --> win_common