---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_lighting_oak(["gui-lighting.oak"])
    gui_common("gui-common")
    thread("thread")
    lib_gui_lighting_oak --> gui_common
    lib_gui_lighting_oak --> thread