---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_graph_oak(["gui-graph.oak"])
    gui_common("gui-common")
    thread("thread")
    lib_gui_graph_oak --> gui_common
    lib_gui_graph_oak --> thread