---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_present_oak(["gui-native-win-vulkan-present.oak"])
    windows("windows")
    gui_thread("gui-thread")
    gui_native_win_vulkan_constants("gui-native-win-vulkan-constants")
    lib_gui_native_win_vulkan_present_oak --> windows
    lib_gui_native_win_vulkan_present_oak --> gui_thread
    lib_gui_native_win_vulkan_present_oak --> gui_native_win_vulkan_constants