---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_draw_ops_oak(["gui-draw-ops.oak"])
    subgraph stdlib_gui ["gui"]
        gui_common("gui-common")
        gui_thread("gui-thread")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end
    lib_gui_draw_ops_oak --> gui_common
    lib_gui_draw_ops_oak --> gui_thread
    lib_gui_draw_ops_oak --> thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    thread --> std