---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        sys["sys"]
        windows_constants["windows-constants"]
        gui_color["gui-color"]
        gui_thread["gui-thread"]
        gui_shader_math["gui-shader-math"]
        windows["windows"]
        windows_gdi["windows-gdi"]
        windows_net["windows-net"]
        gui_fonts["gui-fonts"]
        gui_draw["gui-draw"]
        windows_windowing["windows-windowing"]
        lib_gui_shader_oak(["gui-shader.oak"])
        windows_kernel["windows-kernel"]
        linux_windowing["linux-windowing"]
        std["std"]
        windows_core["windows-core"]
        writes["writes"]
        linux["linux"]
        linux_libc["linux-libc"]
        linux_constants["linux-constants"]
        gui_shader_codegen["gui-shader-codegen"]
        thread["thread"]
        windows_loader["windows-loader"]
        linux_loader["linux-loader"]
        gui_shader_color["gui-shader-color"]
        windows_flags["windows-flags"]
        gui_common["gui-common"]
        linux_core["linux-core"]
        windows_registry["windows-registry"]
        gui_shader_sdf["gui-shader-sdf"]
        gui_shader_noise["gui-shader-noise"]
    end
    sys --> std
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    gui_shader_math --> thread
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_fonts --> gui_common
    gui_fonts --> gui_thread
    gui_draw --> std
    gui_draw --> windows
    gui_draw --> linux
    gui_draw --> gui_common
    gui_draw --> gui_fonts
    gui_draw --> writes
    gui_draw --> gui_thread
    gui_draw --> thread
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    lib_gui_shader_oak --> std
    lib_gui_shader_oak --> gui_draw
    lib_gui_shader_oak --> thread
    lib_gui_shader_oak --> gui_shader_math
    lib_gui_shader_oak --> gui_shader_color
    lib_gui_shader_oak --> gui_shader_noise
    lib_gui_shader_oak --> gui_shader_sdf
    lib_gui_shader_oak --> gui_shader_codegen
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    windows_core --> sys
    windows_core --> windows_constants
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    gui_shader_codegen --> std
    gui_shader_codegen --> thread
    thread --> std
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    gui_shader_color --> gui_color
    gui_shader_color --> gui_shader_math
    gui_shader_color --> thread
    linux_core --> sys
    linux_core --> linux_constants
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    gui_shader_sdf --> gui_shader_math
    gui_shader_sdf --> gui_shader_color
    gui_shader_sdf --> gui_shader_noise
    gui_shader_sdf --> thread
    gui_shader_noise --> gui_shader_math
    gui_shader_noise --> thread