---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_shader_sdf_oak(["gui-shader-sdf.oak"])
    gui_shader_noise("gui-shader-noise")
    thread("thread")
    gui_shader_math("gui-shader-math")
    gui_shader_color("gui-shader-color")
    lib_gui_shader_sdf_oak --> gui_shader_math
    lib_gui_shader_sdf_oak --> gui_shader_color
    lib_gui_shader_sdf_oak --> gui_shader_noise
    lib_gui_shader_sdf_oak --> thread