---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        std["std"]
        lib_gui_lighting_oak(["gui-lighting.oak"])
        gui_common["gui-common"]
    end
    thread --> std
    lib_gui_lighting_oak --> gui_common
    lib_gui_lighting_oak --> thread