---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_registry["windows-registry"]
        thread["thread"]
        gui_native_win_vulkan_constants["gui-native-win-vulkan-constants"]
        windows_gdi["windows-gdi"]
        windows["windows"]
        windows_net["windows-net"]
        gui_native_win_vulkan_init["gui-native-win-vulkan-init"]
        lib_gui_native_win_vulkan_oak(["gui-native-win-vulkan.oak"])
        gui_native_win_vulkan_present["gui-native-win-vulkan-present"]
        writes["writes"]
        windows_constants["windows-constants"]
        windows_kernel["windows-kernel"]
        sys["sys"]
        win_common["win-common"]
        windows_windowing["windows-windowing"]
        windows_core["windows-core"]
        gui_thread["gui-thread"]
        gui_common["gui-common"]
        std["std"]
        windows_loader["windows-loader"]
        gui_native_win_vulkan_swapchain["gui-native-win-vulkan-swapchain"]
        windows_flags["windows-flags"]
    end
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    thread --> std
    gui_native_win_vulkan_constants --> windows
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_native_win_vulkan_init --> windows
    gui_native_win_vulkan_init --> win_common
    gui_native_win_vulkan_init --> gui_thread
    gui_native_win_vulkan_init --> gui_native_win_vulkan_constants
    lib_gui_native_win_vulkan_oak --> gui_thread
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_init
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_swapchain
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_present
    gui_native_win_vulkan_present --> windows
    gui_native_win_vulkan_present --> gui_thread
    gui_native_win_vulkan_present --> gui_native_win_vulkan_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    sys --> std
    win_common --> windows
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_core --> sys
    windows_core --> windows_constants
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    gui_native_win_vulkan_swapchain --> windows
    gui_native_win_vulkan_swapchain --> win_common
    gui_native_win_vulkan_swapchain --> gui_thread
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_constants
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_init