---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_registry["windows-registry"]
        thread["thread"]
        math_stats["math-stats"]
        sys["sys"]
        math["math"]
        windows_loader["windows-loader"]
        gui_input["gui-input"]
        std["std"]
        math_base["math-base"]
        sort["sort"]
        windows["windows"]
        writes["writes"]
        windows_flags["windows-flags"]
        windows_kernel["windows-kernel"]
        windows_gdi["windows-gdi"]
        lib_gui_test_oak(["gui-test.oak"])
        math_geo["math-geo"]
        windows_constants["windows-constants"]
        windows_net["windows-net"]
        windows_windowing["windows-windowing"]
        windows_core["windows-core"]
    end
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sys --> std
    math --> math_base
    math --> math_geo
    math --> math_stats
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    sort --> std
    sort --> thread
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    lib_gui_test_oak --> std
    lib_gui_test_oak --> thread
    lib_gui_test_oak --> math
    lib_gui_test_oak --> windows
    lib_gui_test_oak --> gui_input
    math_geo --> math_base
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_core --> sys
    windows_core --> windows_constants