---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_probe_oak(["gui-native-win-probe.oak"])
    std("std")
    gui_thread("gui-thread")
    gui_common("gui-common")
    windows("windows")
    lib_gui_native_win_probe_oak --> windows
    lib_gui_native_win_probe_oak --> std
    lib_gui_native_win_probe_oak --> gui_thread
    lib_gui_native_win_probe_oak --> gui_common