---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_audio_oak(["gui-audio.oak"])
    std("std")
    math("math")
    gui_thread("gui-thread")
    lib_gui_audio_oak --> std
    lib_gui_audio_oak --> math
    lib_gui_audio_oak --> gui_thread