---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_aa_oak(["gui-aa.oak"])
    thread --> std
    lib_gui_aa_oak --> gui_common
    lib_gui_aa_oak --> gui_color
    lib_gui_aa_oak --> thread
    subgraph stdlib_gui ["gui"]
        gui_common("gui-common")
        gui_color("gui-color")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end