---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        writes["writes"]
        windows_constants["windows-constants"]
        windows["windows"]
        thread["thread"]
        std["std"]
        windows_loader["windows-loader"]
        windows_core["windows-core"]
        gui_common["gui-common"]
        windows_kernel["windows-kernel"]
        windows_gdi["windows-gdi"]
        async_event_bus["event-bus"]
        gui_thread["gui-thread"]
        windows_flags["windows-flags"]
        windows_registry["windows-registry"]
        lib_gui_events_oak(["gui-events.oak"])
        windows_net["windows-net"]
        sys["sys"]
        windows_windowing["windows-windowing"]
        gui_input["gui-input"]
    end
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    thread --> std
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows_core --> sys
    windows_core --> windows_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    async_event_bus --> std
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    lib_gui_events_oak --> windows
    lib_gui_events_oak --> async_event_bus
    lib_gui_events_oak --> gui_common
    lib_gui_events_oak --> gui_input
    lib_gui_events_oak --> gui_thread
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    sys --> std
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std