---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_raster_oak(["gui-raster.oak"])
    subgraph stdlib_gui ["gui"]
        gui_3dmath("gui-3dmath")
        gui_thread("gui-thread")
        gui_common("gui-common")
        gui_lighting("gui-lighting")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end
    gui_3dmath --> gui_common
    gui_3dmath --> thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    lib_gui_raster_oak --> gui_common
    lib_gui_raster_oak --> gui_lighting
    lib_gui_raster_oak --> gui_3dmath
    lib_gui_raster_oak --> gui_thread
    lib_gui_raster_oak --> thread
    gui_lighting --> gui_common
    gui_lighting --> thread
    thread --> std