---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_draw_oak(["gui-draw.oak"])
    subgraph stdlib_windows ["windows"]
        windows_kernel("windows-kernel")
        windows_flags("windows-flags")
        windows_constants("windows-constants")
        windows_loader("windows-loader")
        windows("windows")
        windows_net("windows-net")
        windows_registry("windows-registry")
        windows_windowing("windows-windowing")
        windows_core("windows-core")
        windows_gdi("windows-gdi")
    end
    subgraph stdlib_gui ["gui"]
        gui_common("gui-common")
        gui_fonts("gui-fonts")
        gui_thread("gui-thread")
    end
    subgraph stdlib_linux ["linux"]
        linux_loader("linux-loader")
        linux_libc("linux-libc")
        linux_core("linux-core")
        linux("linux")
        linux_constants("linux-constants")
        linux_windowing("linux-windowing")
    end
    subgraph stdlib_core ["Standard Library"]
        writes("writes")
        thread("thread")
        sys("sys")
        std("std")
    end
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    gui_fonts --> gui_common
    gui_fonts --> gui_thread
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    linux_core --> sys
    linux_core --> linux_constants
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    thread --> std
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    windows_core --> sys
    windows_core --> windows_constants
    lib_gui_draw_oak --> std
    lib_gui_draw_oak --> windows
    lib_gui_draw_oak --> linux
    lib_gui_draw_oak --> gui_common
    lib_gui_draw_oak --> gui_fonts
    lib_gui_draw_oak --> writes
    lib_gui_draw_oak --> gui_thread
    lib_gui_draw_oak --> thread
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    sys --> std