---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_web_oak(["gui-web.oak"])
    subgraph stdlib_gui ["gui"]
        gui_common("gui-common")
        gui_thread("gui-thread")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
    end
    thread --> std
    lib_gui_web_oak --> gui_common
    lib_gui_web_oak --> gui_thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common