---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_lighting_oak(["gui-lighting.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        gui_common("gui-common")
    end
    thread --> std
    lib_gui_lighting_oak --> gui_common
    lib_gui_lighting_oak --> thread