---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_windowing["windows-windowing"]
        windows_loader["windows-loader"]
        gui_input["gui-input"]
        linux_libc["linux-libc"]
        gui_common["gui-common"]
        windows_core["windows-core"]
        windows_flags["windows-flags"]
        windows_gdi["windows-gdi"]
        linux_core["linux-core"]
        windows_kernel["windows-kernel"]
        thread["thread"]
        windows["windows"]
        linux_constants["linux-constants"]
        windows_registry["windows-registry"]
        async_event_bus["event-bus"]
        gui_native_linux["gui-native-linux"]
        linux_windowing["linux-windowing"]
        gui_events["gui-events"]
        linux["linux"]
        linux_loader["linux-loader"]
        sys["sys"]
        writes["writes"]
        windows_constants["windows-constants"]
        windows_net["windows-net"]
        gui_thread["gui-thread"]
        std["std"]
        lib_gui_loop_oak(["gui-loop.oak"])
    end
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    windows_core --> sys
    windows_core --> windows_constants
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    linux_core --> sys
    linux_core --> linux_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    thread --> std
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    async_event_bus --> std
    gui_native_linux --> linux
    gui_native_linux --> gui_common
    gui_native_linux --> gui_thread
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    gui_events --> windows
    gui_events --> async_event_bus
    gui_events --> gui_common
    gui_events --> gui_input
    gui_events --> gui_thread
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    sys --> std
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    lib_gui_loop_oak --> windows
    lib_gui_loop_oak --> gui_events
    lib_gui_loop_oak --> gui_native_linux
    lib_gui_loop_oak --> gui_common
    lib_gui_loop_oak --> gui_thread