---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_init_oak(["gui-native-win-vulkan-init.oak"])
    windows("windows")
    win_common("win-common")
    gui_thread("gui-thread")
    gui_native_win_vulkan_constants("gui-native-win-vulkan-constants")
    lib_gui_native_win_vulkan_init_oak --> windows
    lib_gui_native_win_vulkan_init_oak --> win_common
    lib_gui_native_win_vulkan_init_oak --> gui_thread
    lib_gui_native_win_vulkan_init_oak --> gui_native_win_vulkan_constants