---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_thread_oak(["gui-thread.oak"])
    subgraph stdlib_core ["Standard Library"]
        gui_common("gui-common")
        std("std")
        thread("thread")
    end
    thread --> std
    lib_gui_thread_oak --> std
    lib_gui_thread_oak --> thread
    lib_gui_thread_oak --> gui_common