---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_constants_oak(["gui-native-win-vulkan-constants.oak"])
    windows("windows")
    lib_gui_native_win_vulkan_constants_oak --> windows