---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_constants["windows-constants"]
        gui_native_win_present["gui-native-win-present"]
        gui_native_win_poll["gui-native-win-poll"]
        gui_native_win_vulkan_present["gui-native-win-vulkan-present"]
        sort["sort"]
        windows_windowing["windows-windowing"]
        gui_resolution["gui-resolution"]
        win_common["win-common"]
        windows_gdi["windows-gdi"]
        windows_core["windows-core"]
        gui_native_win_vulkan_constants["gui-native-win-vulkan-constants"]
        std["std"]
        windows_flags["windows-flags"]
        gui_canvas["gui-canvas"]
        windows_net["windows-net"]
        gui_native_win_vulkan_swapchain["gui-native-win-vulkan-swapchain"]
        linux["linux"]
        windows_loader["windows-loader"]
        gui_native_win_opengl["gui-native-win-opengl"]
        gui_native_win_frame["gui-native-win-frame"]
        linux_core["linux-core"]
        lib_gui_native_win_oak(["gui-native-win.oak"])
        gui_native_win_vulkan_init["gui-native-win-vulkan-init"]
        gui_common["gui-common"]
        gui_thread["gui-thread"]
        windows_kernel["windows-kernel"]
        gui_native_win_close["gui-native-win-close"]
        gui_native_win_d3d11["gui-native-win-d3d11"]
        gui_native_win_vulkan["gui-native-win-vulkan"]
        gui_native_win_probe["gui-native-win-probe"]
        linux_libc["linux-libc"]
        sys["sys"]
        linux_windowing["linux-windowing"]
        gui_native_win_ddraw["gui-native-win-ddraw"]
        windows_registry["windows-registry"]
        gui_native_win_icons["gui-native-win-icons"]
        thread["thread"]
        linux_constants["linux-constants"]
        windows["windows"]
        linux_loader["linux-loader"]
        writes["writes"]
    end
    gui_native_win_present --> windows
    gui_native_win_present --> gui_native_win_opengl
    gui_native_win_present --> gui_common
    gui_native_win_present --> gui_thread
    gui_native_win_poll --> windows
    gui_native_win_poll --> gui_thread
    gui_native_win_vulkan_present --> windows
    gui_native_win_vulkan_present --> gui_thread
    gui_native_win_vulkan_present --> gui_native_win_vulkan_constants
    sort --> std
    sort --> thread
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    gui_resolution --> gui_common
    gui_resolution --> gui_thread
    win_common --> windows
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_core --> sys
    windows_core --> windows_constants
    gui_native_win_vulkan_constants --> windows
    gui_canvas --> gui_common
    gui_canvas --> windows
    gui_canvas --> gui_thread
    gui_canvas --> linux
    gui_canvas --> std
    gui_canvas --> sort
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_native_win_vulkan_swapchain --> windows
    gui_native_win_vulkan_swapchain --> win_common
    gui_native_win_vulkan_swapchain --> gui_thread
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_constants
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_init
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    gui_native_win_opengl --> windows
    gui_native_win_opengl --> gui_common
    gui_native_win_opengl --> gui_thread
    gui_native_win_frame --> windows
    gui_native_win_frame --> gui_common
    gui_native_win_frame --> gui_resolution
    gui_native_win_frame --> gui_thread
    linux_core --> sys
    linux_core --> linux_constants
    lib_gui_native_win_oak --> windows
    lib_gui_native_win_oak --> gui_native_win_present
    lib_gui_native_win_oak --> gui_native_win_icons
    lib_gui_native_win_oak --> gui_native_win_frame
    lib_gui_native_win_oak --> gui_native_win_poll
    lib_gui_native_win_oak --> gui_native_win_close
    lib_gui_native_win_oak --> gui_native_win_ddraw
    lib_gui_native_win_oak --> gui_native_win_d3d11
    lib_gui_native_win_oak --> gui_native_win_vulkan
    lib_gui_native_win_oak --> gui_native_win_opengl
    lib_gui_native_win_oak --> gui_native_win_probe
    lib_gui_native_win_oak --> gui_canvas
    lib_gui_native_win_oak --> std
    lib_gui_native_win_oak --> gui_thread
    lib_gui_native_win_oak --> gui_common
    lib_gui_native_win_oak --> win_common
    gui_native_win_vulkan_init --> windows
    gui_native_win_vulkan_init --> win_common
    gui_native_win_vulkan_init --> gui_thread
    gui_native_win_vulkan_init --> gui_native_win_vulkan_constants
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    gui_native_win_close --> windows
    gui_native_win_close --> gui_thread
    gui_native_win_d3d11 --> windows
    gui_native_win_d3d11 --> gui_common
    gui_native_win_d3d11 --> gui_thread
    gui_native_win_d3d11 --> win_common
    gui_native_win_vulkan --> gui_thread
    gui_native_win_vulkan --> gui_native_win_vulkan_init
    gui_native_win_vulkan --> gui_native_win_vulkan_swapchain
    gui_native_win_vulkan --> gui_native_win_vulkan_present
    gui_native_win_probe --> windows
    gui_native_win_probe --> std
    gui_native_win_probe --> gui_thread
    gui_native_win_probe --> gui_common
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    sys --> std
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    gui_native_win_ddraw --> windows
    gui_native_win_ddraw --> gui_common
    gui_native_win_ddraw --> gui_thread
    gui_native_win_ddraw --> win_common
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    gui_native_win_icons --> windows
    gui_native_win_icons --> gui_common
    gui_native_win_icons --> gui_thread
    thread --> std
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core