---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        std["std"]
        lib_gui_aa_oak(["gui-aa.oak"])
        gui_common["gui-common"]
        gui_color["gui-color"]
    end
    thread --> std
    lib_gui_aa_oak --> gui_common
    lib_gui_aa_oak --> gui_color
    lib_gui_aa_oak --> thread