---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_dialogs_oak(["gui-dialogs.oak"])
    windows("windows")
    gui_thread("gui-thread")
    writes("writes")
    std("std")
    lib_gui_dialogs_oak --> std
    lib_gui_dialogs_oak --> windows
    lib_gui_dialogs_oak --> gui_thread
    lib_gui_dialogs_oak --> writes