---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_graph_oak(["gui-graph.oak"])
    thread --> std
    lib_gui_graph_oak --> gui_common
    lib_gui_graph_oak --> thread
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        gui_common("gui-common")
    end