---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_swapchain_oak(["gui-native-win-vulkan-swapchain.oak"])
    subgraph stdlib_windows ["windows"]
        windows_windowing("windows-windowing")
        windows_constants("windows-constants")
        windows_gdi("windows-gdi")
        windows_kernel("windows-kernel")
        windows_net("windows-net")
        windows("windows")
        windows_registry("windows-registry")
        windows_core("windows-core")
        windows_flags("windows-flags")
        windows_loader("windows-loader")
    end
    subgraph stdlib_gui ["gui"]
        gui_common("gui-common")
        gui_native_win_vulkan_init("gui-native-win-vulkan-init")
        gui_native_win_vulkan_constants("gui-native-win-vulkan-constants")
        gui_thread("gui-thread")
    end
    subgraph stdlib_core ["Standard Library"]
        win_common("win-common")
        thread("thread")
        std("std")
        sys("sys")
        writes("writes")
    end
    lib_gui_native_win_vulkan_swapchain_oak --> windows
    lib_gui_native_win_vulkan_swapchain_oak --> win_common
    lib_gui_native_win_vulkan_swapchain_oak --> gui_thread
    lib_gui_native_win_vulkan_swapchain_oak --> gui_native_win_vulkan_constants
    lib_gui_native_win_vulkan_swapchain_oak --> gui_native_win_vulkan_init
    sys --> std
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    win_common --> windows
    thread --> std
    gui_native_win_vulkan_init --> windows
    gui_native_win_vulkan_init --> win_common
    gui_native_win_vulkan_init --> gui_thread
    gui_native_win_vulkan_init --> gui_native_win_vulkan_constants
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_native_win_vulkan_constants --> windows
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    windows_core --> sys
    windows_core --> windows_constants
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common