---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_loop_oak(["gui-loop.oak"])
    subgraph stdlib_linux ["linux"]
        linux_constants("linux-constants")
        linux_loader("linux-loader")
        linux_windowing("linux-windowing")
        linux_core("linux-core")
        linux_libc("linux-libc")
        linux("linux")
    end
    subgraph stdlib_gui ["gui"]
        gui_events("gui-events")
        gui_common("gui-common")
        gui_native_linux("gui-native-linux")
        gui_thread("gui-thread")
        gui_input("gui-input")
    end
    subgraph stdlib_windows ["windows"]
        windows_gdi("windows-gdi")
        windows("windows")
        windows_constants("windows-constants")
        windows_windowing("windows-windowing")
        windows_core("windows-core")
        windows_net("windows-net")
        windows_kernel("windows-kernel")
        windows_loader("windows-loader")
        windows_registry("windows-registry")
        windows_flags("windows-flags")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        async_event_bus("async/event-bus")
        writes("writes")
        sys("sys")
        std("std")
    end
    gui_events --> windows
    gui_events --> async_event_bus
    gui_events --> gui_common
    gui_events --> gui_input
    gui_events --> gui_thread
    thread --> std
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    linux_core --> sys
    linux_core --> linux_constants
    gui_native_linux --> linux
    gui_native_linux --> gui_common
    gui_native_linux --> gui_thread
    lib_gui_loop_oak --> windows
    lib_gui_loop_oak --> gui_events
    lib_gui_loop_oak --> gui_native_linux
    lib_gui_loop_oak --> gui_common
    lib_gui_loop_oak --> gui_thread
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_core --> sys
    windows_core --> windows_constants
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    sys --> std
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    async_event_bus --> std