---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_oak(["gui-native-win.oak"])
    gui_native_win_present("gui-native-win-present")
    gui_native_win_frame("gui-native-win-frame")
    gui_native_win_close("gui-native-win-close")
    gui_common("gui-common")
    windows("windows")
    gui_native_win_poll("gui-native-win-poll")
    gui_native_win_opengl("gui-native-win-opengl")
    gui_native_win_probe("gui-native-win-probe")
    std("std")
    gui_native_win_icons("gui-native-win-icons")
    gui_native_win_ddraw("gui-native-win-ddraw")
    gui_native_win_vulkan("gui-native-win-vulkan")
    win_common("win-common")
    gui_native_win_d3d11("gui-native-win-d3d11")
    gui_canvas("gui-canvas")
    gui_thread("gui-thread")
    lib_gui_native_win_oak --> windows
    lib_gui_native_win_oak --> gui_native_win_present
    lib_gui_native_win_oak --> gui_native_win_icons
    lib_gui_native_win_oak --> gui_native_win_frame
    lib_gui_native_win_oak --> gui_native_win_poll
    lib_gui_native_win_oak --> gui_native_win_close
    lib_gui_native_win_oak --> gui_native_win_ddraw
    lib_gui_native_win_oak --> gui_native_win_d3d11
    lib_gui_native_win_oak --> gui_native_win_vulkan
    lib_gui_native_win_oak --> gui_native_win_opengl
    lib_gui_native_win_oak --> gui_native_win_probe
    lib_gui_native_win_oak --> gui_canvas
    lib_gui_native_win_oak --> std
    lib_gui_native_win_oak --> gui_thread
    lib_gui_native_win_oak --> gui_common
    lib_gui_native_win_oak --> win_common