---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_oak(["gui-native-win-vulkan.oak"])
    subgraph stdlib_gui ["gui"]
        gui_native_win_vulkan_swapchain("gui-native-win-vulkan-swapchain")
        gui_native_win_vulkan_present("gui-native-win-vulkan-present")
        gui_native_win_vulkan_init("gui-native-win-vulkan-init")
        gui_common("gui-common")
        gui_native_win_vulkan_constants("gui-native-win-vulkan-constants")
        gui_thread("gui-thread")
    end
    subgraph stdlib_windows ["windows"]
        windows_core("windows-core")
        windows("windows")
        windows_gdi("windows-gdi")
        windows_kernel("windows-kernel")
        windows_net("windows-net")
        windows_loader("windows-loader")
        windows_flags("windows-flags")
        windows_windowing("windows-windowing")
        windows_constants("windows-constants")
        windows_registry("windows-registry")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        writes("writes")
        std("std")
        win_common("win-common")
        thread("thread")
    end
    gui_native_win_vulkan_swapchain --> windows
    gui_native_win_vulkan_swapchain --> win_common
    gui_native_win_vulkan_swapchain --> gui_thread
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_constants
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_init
    thread --> std
    gui_native_win_vulkan_present --> windows
    gui_native_win_vulkan_present --> gui_thread
    gui_native_win_vulkan_present --> gui_native_win_vulkan_constants
    windows_core --> sys
    windows_core --> windows_constants
    sys --> std
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    win_common --> windows
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    gui_native_win_vulkan_init --> windows
    gui_native_win_vulkan_init --> win_common
    gui_native_win_vulkan_init --> gui_thread
    gui_native_win_vulkan_init --> gui_native_win_vulkan_constants
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    lib_gui_native_win_vulkan_oak --> gui_thread
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_init
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_swapchain
    lib_gui_native_win_vulkan_oak --> gui_native_win_vulkan_present
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    gui_native_win_vulkan_constants --> windows
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common