---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_loader["windows-loader"]
        gui_thread["gui-thread"]
        writes["writes"]
        thread["thread"]
        windows_constants["windows-constants"]
        linux_constants["linux-constants"]
        linux_windowing["linux-windowing"]
        linux_core["linux-core"]
        windows["windows"]
        windows_kernel["windows-kernel"]
        windows_net["windows-net"]
        std["std"]
        sys["sys"]
        linux_loader["linux-loader"]
        windows_registry["windows-registry"]
        gui_fonts["gui-fonts"]
        windows_gdi["windows-gdi"]
        lib_gui_draw_oak(["gui-draw.oak"])
        windows_windowing["windows-windowing"]
        gui_common["gui-common"]
        linux_libc["linux-libc"]
        linux["linux"]
        windows_flags["windows-flags"]
        windows_core["windows-core"]
    end
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    thread --> std
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    linux_core --> sys
    linux_core --> linux_constants
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    sys --> std
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    gui_fonts --> gui_common
    gui_fonts --> gui_thread
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    lib_gui_draw_oak --> std
    lib_gui_draw_oak --> windows
    lib_gui_draw_oak --> linux
    lib_gui_draw_oak --> gui_common
    lib_gui_draw_oak --> gui_fonts
    lib_gui_draw_oak --> writes
    lib_gui_draw_oak --> gui_thread
    lib_gui_draw_oak --> thread
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    windows_core --> sys
    windows_core --> windows_constants