---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        gui_thread["gui-thread"]
        thread["thread"]
        std["std"]
        lib_gui_web_oak(["gui-web.oak"])
        gui_common["gui-common"]
    end
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    thread --> std
    lib_gui_web_oak --> gui_common
    lib_gui_web_oak --> gui_thread
    lib_gui_web_oak --> std