---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        gui_common["gui-common"]
        thread["thread"]
        std["std"]
        lib_gui_2d_oak(["gui-2d.oak"])
    end
    thread --> std
    lib_gui_2d_oak --> gui_common
    lib_gui_2d_oak --> thread