---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        sort["sort"]
        math_base["math-base"]
        math_stats["math-stats"]
        gui_thread["gui-thread"]
        gui_common["gui-common"]
        math["math"]
        math_geo["math-geo"]
        thread["thread"]
        std["std"]
        lib_gui_audio_oak(["gui-audio.oak"])
    end
    sort --> std
    sort --> thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    math --> math_base
    math --> math_geo
    math --> math_stats
    math_geo --> math_base
    thread --> std
    lib_gui_audio_oak --> std
    lib_gui_audio_oak --> math
    lib_gui_audio_oak --> gui_thread