---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_present_oak(["gui-native-win-present.oak"])
    gui_thread("gui-thread")
    windows("windows")
    gui_native_win_opengl("gui-native-win-opengl")
    gui_common("gui-common")
    lib_gui_native_win_present_oak --> windows
    lib_gui_native_win_present_oak --> gui_native_win_opengl
    lib_gui_native_win_present_oak --> gui_common
    lib_gui_native_win_present_oak --> gui_thread