---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_video_oak(["gui-video.oak"])
    std("std")
    video("video")
    gui_color("gui-color")
    gui_shader("gui-shader")
    thread("thread")
    lib_gui_video_oak --> std
    lib_gui_video_oak --> video
    lib_gui_video_oak --> gui_color
    lib_gui_video_oak --> gui_shader
    lib_gui_video_oak --> thread