---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_3dmath_oak(["gui-3dmath.oak"])
    gui_common("gui-common")
    thread("thread")
    lib_gui_3dmath_oak --> gui_common
    lib_gui_3dmath_oak --> thread