---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        gui_color["gui-color"]
        gui_shader_math["gui-shader-math"]
        thread["thread"]
        std["std"]
        lib_gui_shader_color_oak(["gui-shader-color.oak"])
    end
    gui_shader_math --> thread
    thread --> std
    lib_gui_shader_color_oak --> gui_color
    lib_gui_shader_color_oak --> gui_shader_math
    lib_gui_shader_color_oak --> thread