---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_test_oak(["gui-test.oak"])
    std("std")
    thread("thread")
    math("math")
    windows("windows")
    gui_input("gui-input")
    lib_gui_test_oak --> std
    lib_gui_test_oak --> thread
    lib_gui_test_oak --> math
    lib_gui_test_oak --> windows
    lib_gui_test_oak --> gui_input