---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_native_win_vulkan_constants_oak(["gui-native-win-vulkan-constants.oak"])
    subgraph stdlib_windows ["windows"]
        windows_windowing("windows-windowing")
        windows_loader("windows-loader")
        windows("windows")
        windows_net("windows-net")
        windows_core("windows-core")
        windows_registry("windows-registry")
        windows_gdi("windows-gdi")
        windows_kernel("windows-kernel")
        windows_constants("windows-constants")
        windows_flags("windows-flags")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        writes("writes")
        sys("sys")
    end
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    lib_gui_native_win_vulkan_constants_oak --> windows
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_core --> sys
    windows_core --> windows_constants
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    sys --> std