---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        gui_shader_color["gui-shader-color"]
        gui_color["gui-color"]
        gui_shader_noise["gui-shader-noise"]
        lib_gui_shader_sdf_oak(["gui-shader-sdf.oak"])
        gui_shader_math["gui-shader-math"]
        thread["thread"]
    end
    gui_shader_color --> gui_color
    gui_shader_color --> gui_shader_math
    gui_shader_color --> thread
    gui_shader_noise --> gui_shader_math
    gui_shader_noise --> thread
    lib_gui_shader_sdf_oak --> gui_shader_math
    lib_gui_shader_sdf_oak --> gui_shader_color
    lib_gui_shader_sdf_oak --> gui_shader_noise
    lib_gui_shader_sdf_oak --> thread
    gui_shader_math --> thread
    thread --> std