---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_mesh_oak(["gui-mesh.oak"])
    gui_common("gui-common")
    thread("thread")
    lib_gui_mesh_oak --> gui_common
    lib_gui_mesh_oak --> thread