---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_canvas_oak(["gui-canvas.oak"])
    gui_common("gui-common")
    windows("windows")
    gui_thread("gui-thread")
    linux("linux")
    std("std")
    sort("sort")
    lib_gui_canvas_oak --> gui_common
    lib_gui_canvas_oak --> windows
    lib_gui_canvas_oak --> gui_thread
    lib_gui_canvas_oak --> linux
    lib_gui_canvas_oak --> std
    lib_gui_canvas_oak --> sort