---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_shader_codegen_oak(["gui-shader-codegen.oak"])
    thread("thread")
    std("std")
    lib_gui_shader_codegen_oak --> std
    lib_gui_shader_codegen_oak --> thread