---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_gpu_info_oak(["gui-gpu-info.oak"])
    lib_gui_gpu_info_oak --> std
    lib_gui_gpu_info_oak --> math
    lib_gui_gpu_info_oak --> gui_thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    thread --> std
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    math --> math_base
    math --> math_geo
    math --> math_stats
    math_geo --> math_base
    sort --> std
    sort --> thread
    subgraph stdlib_gui ["gui"]
        gui_common("gui-common")
        gui_thread("gui-thread")
    end
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math_stats("math-stats")
        math("math")
        math_geo("math-geo")
    end
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        sort("sort")
    end