---
title: Module Dependency Graph
---
flowchart LR
    lib_gui_test_oak(["gui-test.oak"])
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math("math")
        math_stats("math-stats")
        math_geo("math-geo")
    end
    subgraph stdlib_windows ["windows"]
        windows_flags("windows-flags")
        windows_core("windows-core")
        windows("windows")
        windows_registry("windows-registry")
        windows_loader("windows-loader")
        windows_net("windows-net")
        windows_constants("windows-constants")
        windows_kernel("windows-kernel")
        windows_windowing("windows-windowing")
        windows_gdi("windows-gdi")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        thread("thread")
        writes("writes")
        sort("sort")
        std("std")
        gui_input("gui-input")
    end
    windows_core --> sys
    windows_core --> windows_constants
    sys --> std
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    math --> math_base
    math --> math_geo
    math --> math_stats
    sort --> std
    sort --> thread
    lib_gui_test_oak --> std
    lib_gui_test_oak --> thread
    lib_gui_test_oak --> math
    lib_gui_test_oak --> windows
    lib_gui_test_oak --> gui_input
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    math_geo --> math_base
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants