---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_loader["windows-loader"]
        std["std"]
        windows_constants["windows-constants"]
        windows_flags["windows-flags"]
        sys["sys"]
        windows["windows"]
        windows_gdi["windows-gdi"]
        gui_common["gui-common"]
        windows_core["windows-core"]
        lib_gui_native_win_icons_oak(["gui-native-win-icons.oak"])
        gui_thread["gui-thread"]
        thread["thread"]
        windows_windowing["windows-windowing"]
        writes["writes"]
        windows_registry["windows-registry"]
        windows_net["windows-net"]
        windows_kernel["windows-kernel"]
    end
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    sys --> std
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_core --> sys
    windows_core --> windows_constants
    lib_gui_native_win_icons_oak --> windows
    lib_gui_native_win_icons_oak --> gui_common
    lib_gui_native_win_icons_oak --> gui_thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    thread --> std
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags