---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        sys["sys"]
        linux_core["linux-core"]
        linux_loader["linux-loader"]
        thread["thread"]
        linux_libc["linux-libc"]
        linux_constants["linux-constants"]
        lib_gui_native_linux_oak(["gui-native-linux.oak"])
        std["std"]
        gui_thread["gui-thread"]
        linux_windowing["linux-windowing"]
        writes["writes"]
        gui_common["gui-common"]
        linux["linux"]
    end
    sys --> std
    linux_core --> sys
    linux_core --> linux_constants
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    thread --> std
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    lib_gui_native_linux_oak --> linux
    lib_gui_native_linux_oak --> gui_common
    lib_gui_native_linux_oak --> gui_thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc