---
title: Module Dependency Graph
---
flowchart LR
    lib_GUI_oak(["GUI.oak"])
    subgraph stdlib_gui ["gui"]
        gui_native_win_frame("gui-native-win-frame")
        gui_fonts("gui-fonts")
        gui_draw_ops("gui-draw-ops")
        gui_draw("gui-draw")
        gui_native_win_d3d11("gui-native-win-d3d11")
        gui_loop("gui-loop")
        gui_native_win_poll("gui-native-win-poll")
        gui_theme("gui-theme")
        gui_filedrop("gui-filedrop")
        gui_form("gui-form")
        gui_render("gui-render")
        gui_shader_codegen("gui-shader-codegen")
        gui_native_win_present("gui-native-win-present")
        gui_shader_math("gui-shader-math")
        gui_gpu_info("gui-gpu-info")
        gui_color("gui-color")
        gui_resolution("gui-resolution")
        gui_mesh("gui-mesh")
        gui_native_win_ddraw("gui-native-win-ddraw")
        gui_dialogs("gui-dialogs")
        gui_2d("gui-2d")
        gui_leak_detect("gui-leak-detect")
        gui_systray("gui-systray")
        gui_accessibility("gui-accessibility")
        gui_native_win_vulkan_present("gui-native-win-vulkan-present")
        gui_native_win_vulkan_constants("gui-native-win-vulkan-constants")
        gui_native_win_probe("gui-native-win-probe")
        gui_native_win_icons("gui-native-win-icons")
        gui_shader_color("gui-shader-color")
        gui_print("gui-print")
        gui_native_win_vulkan_swapchain("gui-native-win-vulkan-swapchain")
        gui_audio("gui-audio")
        gui_native_win("gui-native-win")
        gui_native_win_close("gui-native-win-close")
        gui_video("gui-video")
        gui_3dmath("gui-3dmath")
        gui_test("gui-test")
        gui_menus("gui-menus")
        gui_raster("gui-raster")
        gui_common("gui-common")
        gui_native_win_vulkan_init("gui-native-win-vulkan-init")
        gui_graph("gui-graph")
        gui_events("gui-events")
        gui_web("gui-web")
        gui_shader_sdf("gui-shader-sdf")
        gui_clipboard("gui-clipboard")
        gui_shader_noise("gui-shader-noise")
        gui_lighting("gui-lighting")
        gui_gamepad("gui-gamepad")
        gui_native_win_vulkan("gui-native-win-vulkan")
        gui_aa("gui-aa")
        gui_native_linux("gui-native-linux")
        gui_canvas("gui-canvas")
        gui_shader("gui-shader")
        gui_input("gui-input")
        gui_native_win_opengl("gui-native-win-opengl")
        gui_thread("gui-thread")
    end
    subgraph stdlib_windows ["windows"]
        windows_registry("windows-registry")
        windows_core("windows-core")
        windows("windows")
        windows_net("windows-net")
        windows_kernel("windows-kernel")
        windows_loader("windows-loader")
        windows_windowing("windows-windowing")
        windows_gdi("windows-gdi")
        windows_constants("windows-constants")
        windows_flags("windows-flags")
    end
    subgraph stdlib_math ["math"]
        math_geo("math-geo")
        math("math")
        math_stats("math-stats")
        math_base("math-base")
    end
    subgraph stdlib_linux ["linux"]
        linux_loader("linux-loader")
        linux_libc("linux-libc")
        linux_constants("linux-constants")
        linux_windowing("linux-windowing")
        linux_core("linux-core")
        linux("linux")
    end
    subgraph stdlib_core ["Standard Library"]
        video("video")
        thread("thread")
        std("std")
        sort("sort")
        async_event_bus("async/event-bus")
        sys("sys")
        writes("writes")
        win_common("win-common")
    end
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    thread --> std
    windows_core --> sys
    windows_core --> windows_constants
    gui_native_win_frame --> windows
    gui_native_win_frame --> gui_common
    gui_native_win_frame --> gui_resolution
    gui_native_win_frame --> gui_thread
    gui_fonts --> gui_common
    gui_fonts --> gui_thread
    gui_draw_ops --> gui_common
    gui_draw_ops --> gui_thread
    gui_draw_ops --> thread
    gui_draw --> std
    gui_draw --> windows
    gui_draw --> linux
    gui_draw --> gui_common
    gui_draw --> gui_fonts
    gui_draw --> writes
    gui_draw --> gui_thread
    gui_draw --> thread
    gui_native_win_d3d11 --> windows
    gui_native_win_d3d11 --> gui_common
    gui_native_win_d3d11 --> gui_thread
    gui_native_win_d3d11 --> win_common
    gui_loop --> windows
    gui_loop --> gui_events
    gui_loop --> gui_native_linux
    gui_loop --> gui_common
    gui_loop --> gui_thread
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    gui_native_win_poll --> windows
    gui_native_win_poll --> gui_thread
    gui_theme --> windows
    gui_theme --> gui_thread
    gui_theme --> writes
    gui_filedrop --> std
    gui_filedrop --> windows
    gui_filedrop --> gui_thread
    gui_filedrop --> writes
    gui_form --> std
    gui_form --> gui_common
    gui_form --> gui_input
    gui_form --> gui_thread
    math_geo --> math_base
    sort --> std
    sort --> thread
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    gui_render --> gui_common
    gui_render --> gui_thread
    gui_render --> thread
    gui_shader_codegen --> std
    gui_shader_codegen --> thread
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    gui_native_win_present --> windows
    gui_native_win_present --> gui_native_win_opengl
    gui_native_win_present --> gui_common
    gui_native_win_present --> gui_thread
    gui_shader_math --> thread
    gui_gpu_info --> std
    gui_gpu_info --> math
    gui_gpu_info --> gui_thread
    lib_GUI_oak --> std
    lib_GUI_oak --> windows
    lib_GUI_oak --> linux
    lib_GUI_oak --> gui_mesh
    lib_GUI_oak --> gui_render
    lib_GUI_oak --> gui_3dmath
    lib_GUI_oak --> gui_2d
    lib_GUI_oak --> gui_raster
    lib_GUI_oak --> gui_lighting
    lib_GUI_oak --> gui_web
    lib_GUI_oak --> gui_native_win
    lib_GUI_oak --> gui_native_linux
    lib_GUI_oak --> gui_draw
    lib_GUI_oak --> gui_color
    lib_GUI_oak --> gui_events
    lib_GUI_oak --> gui_input
    lib_GUI_oak --> gui_graph
    lib_GUI_oak --> gui_form
    lib_GUI_oak --> gui_loop
    lib_GUI_oak --> gui_shader
    lib_GUI_oak --> gui_fonts
    lib_GUI_oak --> gui_video
    lib_GUI_oak --> gui_resolution
    lib_GUI_oak --> gui_canvas
    lib_GUI_oak --> gui_accessibility
    lib_GUI_oak --> gui_clipboard
    lib_GUI_oak --> gui_filedrop
    lib_GUI_oak --> gui_audio
    lib_GUI_oak --> gui_gamepad
    lib_GUI_oak --> gui_aa
    lib_GUI_oak --> gui_draw_ops
    lib_GUI_oak --> gui_gpu_info
    lib_GUI_oak --> gui_leak_detect
    lib_GUI_oak --> gui_test
    lib_GUI_oak --> gui_dialogs
    lib_GUI_oak --> gui_menus
    lib_GUI_oak --> gui_print
    lib_GUI_oak --> gui_theme
    lib_GUI_oak --> gui_systray
    lib_GUI_oak --> gui_thread
    lib_GUI_oak --> gui_common
    gui_resolution --> gui_common
    gui_resolution --> gui_thread
    gui_mesh --> gui_common
    gui_mesh --> thread
    gui_native_win_ddraw --> windows
    gui_native_win_ddraw --> gui_common
    gui_native_win_ddraw --> gui_thread
    gui_native_win_ddraw --> win_common
    gui_dialogs --> std
    gui_dialogs --> windows
    gui_dialogs --> gui_thread
    gui_dialogs --> writes
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    gui_2d --> gui_common
    gui_2d --> thread
    gui_leak_detect --> std
    gui_leak_detect --> gui_thread
    gui_leak_detect --> math
    gui_leak_detect --> windows
    gui_systray --> std
    gui_systray --> windows
    gui_systray --> gui_thread
    gui_systray --> writes
    gui_accessibility --> sys
    gui_accessibility --> windows
    gui_accessibility --> gui_thread
    gui_accessibility --> writes
    gui_native_win_vulkan_present --> windows
    gui_native_win_vulkan_present --> gui_thread
    gui_native_win_vulkan_present --> gui_native_win_vulkan_constants
    gui_native_win_vulkan_constants --> windows
    math --> math_base
    math --> math_geo
    math --> math_stats
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    gui_native_win_probe --> windows
    gui_native_win_probe --> std
    gui_native_win_probe --> gui_thread
    gui_native_win_probe --> gui_common
    gui_native_win_icons --> windows
    gui_native_win_icons --> gui_common
    gui_native_win_icons --> gui_thread
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    async_event_bus --> std
    gui_shader_color --> gui_color
    gui_shader_color --> gui_shader_math
    gui_shader_color --> thread
    gui_print --> sys
    gui_print --> windows
    gui_print --> gui_thread
    gui_print --> writes
    gui_native_win_vulkan_swapchain --> windows
    gui_native_win_vulkan_swapchain --> win_common
    gui_native_win_vulkan_swapchain --> gui_thread
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_constants
    gui_native_win_vulkan_swapchain --> gui_native_win_vulkan_init
    gui_audio --> std
    gui_audio --> math
    gui_audio --> gui_thread
    gui_native_win --> windows
    gui_native_win --> gui_native_win_present
    gui_native_win --> gui_native_win_icons
    gui_native_win --> gui_native_win_frame
    gui_native_win --> gui_native_win_poll
    gui_native_win --> gui_native_win_close
    gui_native_win --> gui_native_win_ddraw
    gui_native_win --> gui_native_win_d3d11
    gui_native_win --> gui_native_win_vulkan
    gui_native_win --> gui_native_win_opengl
    gui_native_win --> gui_native_win_probe
    gui_native_win --> gui_canvas
    gui_native_win --> std
    gui_native_win --> gui_thread
    gui_native_win --> gui_common
    gui_native_win --> win_common
    gui_native_win_close --> windows
    gui_native_win_close --> gui_thread
    gui_video --> std
    gui_video --> video
    gui_video --> gui_color
    gui_video --> gui_shader
    gui_video --> thread
    gui_3dmath --> gui_common
    gui_3dmath --> thread
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    gui_test --> std
    gui_test --> thread
    gui_test --> math
    gui_test --> windows
    gui_test --> gui_input
    gui_menus --> std
    gui_menus --> windows
    gui_menus --> gui_thread
    gui_menus --> writes
    gui_raster --> gui_common
    gui_raster --> gui_lighting
    gui_raster --> gui_3dmath
    gui_raster --> gui_thread
    gui_raster --> thread
    gui_native_win_vulkan_init --> windows
    gui_native_win_vulkan_init --> win_common
    gui_native_win_vulkan_init --> gui_thread
    gui_native_win_vulkan_init --> gui_native_win_vulkan_constants
    gui_graph --> gui_common
    gui_graph --> thread
    gui_events --> windows
    gui_events --> async_event_bus
    gui_events --> gui_common
    gui_events --> gui_input
    gui_events --> gui_thread
    gui_web --> gui_common
    gui_web --> gui_thread
    win_common --> windows
    video --> std
    video --> math
    video --> thread
    gui_shader_sdf --> gui_shader_math
    gui_shader_sdf --> gui_shader_color
    gui_shader_sdf --> gui_shader_noise
    gui_shader_sdf --> thread
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    gui_clipboard --> windows
    gui_clipboard --> gui_thread
    gui_clipboard --> writes
    linux_core --> sys
    linux_core --> linux_constants
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    gui_shader_noise --> gui_shader_math
    gui_shader_noise --> thread
    gui_lighting --> gui_common
    gui_lighting --> thread
    gui_gamepad --> sys
    gui_gamepad --> windows
    gui_gamepad --> gui_thread
    gui_gamepad --> writes
    gui_native_win_vulkan --> gui_thread
    gui_native_win_vulkan --> gui_native_win_vulkan_init
    gui_native_win_vulkan --> gui_native_win_vulkan_swapchain
    gui_native_win_vulkan --> gui_native_win_vulkan_present
    linux --> sys
    linux --> writes
    linux --> linux_constants
    linux --> linux_core
    linux --> linux_loader
    linux --> linux_windowing
    linux --> linux_libc
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    gui_aa --> gui_common
    gui_aa --> gui_color
    gui_aa --> thread
    gui_native_linux --> linux
    gui_native_linux --> gui_common
    gui_native_linux --> gui_thread
    gui_canvas --> gui_common
    gui_canvas --> windows
    gui_canvas --> gui_thread
    gui_canvas --> linux
    gui_canvas --> std
    gui_canvas --> sort
    sys --> std
    gui_shader --> std
    gui_shader --> gui_draw
    gui_shader --> thread
    gui_shader --> gui_shader_math
    gui_shader --> gui_shader_color
    gui_shader --> gui_shader_noise
    gui_shader --> gui_shader_sdf
    gui_shader --> gui_shader_codegen
    gui_native_win_opengl --> windows
    gui_native_win_opengl --> gui_common
    gui_native_win_opengl --> gui_thread
    gui_thread --> std
    gui_thread --> thread
    gui_thread --> gui_common