---
title: Module Dependency Graph
---
flowchart LR
    lib_GUI_oak(["GUI.oak"])
    gui_gpu_info("gui-gpu-info")
    gui_leak_detect("gui-leak-detect")
    gui_events("gui-events")
    gui_resolution("gui-resolution")
    gui_common("gui-common")
    gui_render("gui-render")
    gui_native_linux("gui-native-linux")
    gui_draw("gui-draw")
    gui_input("gui-input")
    gui_form("gui-form")
    gui_loop("gui-loop")
    gui_accessibility("gui-accessibility")
    gui_clipboard("gui-clipboard")
    windows("windows")
    gui_raster("gui-raster")
    gui_color("gui-color")
    gui_canvas("gui-canvas")
    gui_aa("gui-aa")
    gui_draw_ops("gui-draw-ops")
    gui_test("gui-test")
    gui_theme("gui-theme")
    gui_mesh("gui-mesh")
    gui_graph("gui-graph")
    gui_filedrop("gui-filedrop")
    gui_3dmath("gui-3dmath")
    gui_web("gui-web")
    gui_systray("gui-systray")
    gui_thread("gui-thread")
    linux("linux")
    gui_2d("gui-2d")
    gui_lighting("gui-lighting")
    gui_native_win("gui-native-win")
    gui_shader("gui-shader")
    gui_audio("gui-audio")
    gui_menus("gui-menus")
    gui_gamepad("gui-gamepad")
    gui_dialogs("gui-dialogs")
    gui_print("gui-print")
    std("std")
    gui_fonts("gui-fonts")
    gui_video("gui-video")
    lib_GUI_oak --> std
    lib_GUI_oak --> windows
    lib_GUI_oak --> linux
    lib_GUI_oak --> gui_mesh
    lib_GUI_oak --> gui_render
    lib_GUI_oak --> gui_3dmath
    lib_GUI_oak --> gui_2d
    lib_GUI_oak --> gui_raster
    lib_GUI_oak --> gui_lighting
    lib_GUI_oak --> gui_web
    lib_GUI_oak --> gui_native_win
    lib_GUI_oak --> gui_native_linux
    lib_GUI_oak --> gui_draw
    lib_GUI_oak --> gui_color
    lib_GUI_oak --> gui_events
    lib_GUI_oak --> gui_input
    lib_GUI_oak --> gui_graph
    lib_GUI_oak --> gui_form
    lib_GUI_oak --> gui_loop
    lib_GUI_oak --> gui_shader
    lib_GUI_oak --> gui_fonts
    lib_GUI_oak --> gui_video
    lib_GUI_oak --> gui_resolution
    lib_GUI_oak --> gui_canvas
    lib_GUI_oak --> gui_accessibility
    lib_GUI_oak --> gui_clipboard
    lib_GUI_oak --> gui_filedrop
    lib_GUI_oak --> gui_audio
    lib_GUI_oak --> gui_gamepad
    lib_GUI_oak --> gui_aa
    lib_GUI_oak --> gui_draw_ops
    lib_GUI_oak --> gui_gpu_info
    lib_GUI_oak --> gui_leak_detect
    lib_GUI_oak --> gui_test
    lib_GUI_oak --> gui_dialogs
    lib_GUI_oak --> gui_menus
    lib_GUI_oak --> gui_print
    lib_GUI_oak --> gui_theme
    lib_GUI_oak --> gui_systray
    lib_GUI_oak --> gui_thread
    lib_GUI_oak --> gui_common