---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_http_oak(["http.oak"])
        fs["fs"]
        thread["thread"]
        std["std"]
        fmt["fmt"]
        sort["sort"]
        json["json"]
        str["str"]
    end
    lib_http_oak --> std
    lib_http_oak --> str
    lib_http_oak --> fs
    lib_http_oak --> fmt
    lib_http_oak --> sort
    lib_http_oak --> json
    lib_http_oak --> thread
    fs --> thread
    thread --> std
    fmt --> std
    sort --> std
    sort --> thread
    json --> std
    json --> str
    str --> std