---
title: Module Dependency Graph
---
flowchart LR
    lib_http_oak(["http.oak"])
    sort("sort")
    json("json")
    thread("thread")
    std("std")
    str("str")
    fs("fs")
    fmt("fmt")
    lib_http_oak --> std
    lib_http_oak --> str
    lib_http_oak --> fs
    lib_http_oak --> fmt
    lib_http_oak --> sort
    lib_http_oak --> json
    lib_http_oak --> thread