---
title: Module Dependency Graph
---
flowchart LR
    lib_http_oak(["http.oak"])
    subgraph stdlib_core ["Standard Library"]
        json("json")
        std("std")
        str("str")
        fs("fs")
        thread("thread")
        fmt("fmt")
        sort("sort")
    end
    fs --> thread
    thread --> std
    fmt --> std
    sort --> std
    sort --> thread
    json --> std
    json --> str
    lib_http_oak --> std
    lib_http_oak --> str
    lib_http_oak --> fs
    lib_http_oak --> fmt
    lib_http_oak --> sort
    lib_http_oak --> json
    lib_http_oak --> thread
    str --> std