---
title: Module Dependency Graph
---
flowchart LR
    lib_image_oak(["image.oak"])
    subgraph stdlib_image ["image"]
        image_ico("image-ico")
        image_ppm("image-ppm")
        image_tga("image-tga")
        image_qoi("image-qoi")
        image_bmp("image-bmp")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
    end
    str --> std
    image_ico --> std
    image_ico --> str
    image_ppm --> std
    image_ppm --> str
    image_tga --> std
    image_tga --> str
    image_qoi --> std
    image_qoi --> str
    lib_image_oak --> image_bmp
    lib_image_oak --> image_ico
    lib_image_oak --> image_ppm
    lib_image_oak --> image_tga
    lib_image_oak --> image_qoi
    image_bmp --> std
    image_bmp --> str