---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        image_bmp["image-bmp"]
        std["std"]
        str["str"]
        image_ico["image-ico"]
        image_ppm["image-ppm"]
        image_tga["image-tga"]
        image_qoi["image-qoi"]
        lib_image_oak(["image.oak"])
    end
    image_bmp --> std
    image_bmp --> str
    str --> std
    image_ico --> std
    image_ico --> str
    image_ppm --> std
    image_ppm --> str
    image_tga --> std
    image_tga --> str
    image_qoi --> std
    image_qoi --> str
    lib_image_oak --> image_bmp
    lib_image_oak --> image_ico
    lib_image_oak --> image_ppm
    lib_image_oak --> image_tga
    lib_image_oak --> image_qoi