---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        str["str"]
        lib_image_tga_oak(["image-tga.oak"])
        std["std"]
    end
    str --> std
    lib_image_tga_oak --> std
    lib_image_tga_oak --> str