---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_image_qoi_oak(["image-qoi.oak"])
        std["std"]
        str["str"]
    end
    lib_image_qoi_oak --> std
    lib_image_qoi_oak --> str
    str --> std