---
title: Module Dependency Graph
---
flowchart LR
    lib_imap_oak(["imap.oak"])
    lib_imap_oak --> std
    lib_imap_oak --> str
    lib_imap_oak --> thread
    lib_imap_oak --> socket
    str --> std
    thread --> std
    subgraph stdlib_core ["Standard Library"]
        socket("socket")
        std("std")
        str("str")
        thread("thread")
    end