---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        str["str"]
        thread["thread"]
        socket["socket"]
        lib_imap_oak(["imap.oak"])
        std["std"]
    end
    str --> std
    thread --> std
    lib_imap_oak --> std
    lib_imap_oak --> str
    lib_imap_oak --> thread
    lib_imap_oak --> socket