---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        str["str"]
        lib_json_oak(["json.oak"])
    end
    str --> std
    lib_json_oak --> std
    lib_json_oak --> str