---
title: Module Dependency Graph
---
flowchart LR
    lib_linux_loader_oak(["linux-loader.oak"])
    sys("sys")
    linux_constants("linux-constants")
    linux_core("linux-core")
    lib_linux_loader_oak --> sys
    lib_linux_loader_oak --> linux_constants
    lib_linux_loader_oak --> linux_core