---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        linux_core["linux-core"]
        lib_Linux_oak(["Linux.oak"])
        std["std"]
        writes["writes"]
        sys["sys"]
        linux_constants["linux-constants"]
        linux_loader["linux-loader"]
        linux_libc["linux-libc"]
        linux_windowing["linux-windowing"]
    end
    linux_core --> sys
    linux_core --> linux_constants
    lib_Linux_oak --> sys
    lib_Linux_oak --> writes
    lib_Linux_oak --> linux_constants
    lib_Linux_oak --> linux_core
    lib_Linux_oak --> linux_loader
    lib_Linux_oak --> linux_windowing
    lib_Linux_oak --> linux_libc
    sys --> std
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader