---
title: Module Dependency Graph
---
flowchart LR
    lib_linux_core_oak(["linux-core.oak"])
    lib_linux_core_oak --> sys
    lib_linux_core_oak --> linux_constants
    sys --> std
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        std("std")
        linux_constants("linux-constants")
    end