---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        linux_core["linux-core"]
        sys["sys"]
        std["std"]
        linux_constants["linux-constants"]
        linux_loader["linux-loader"]
        lib_linux_libc_oak(["linux-libc.oak"])
        writes["writes"]
    end
    linux_core --> sys
    linux_core --> linux_constants
    sys --> std
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    lib_linux_libc_oak --> sys
    lib_linux_libc_oak --> writes
    lib_linux_libc_oak --> linux_constants
    lib_linux_libc_oak --> linux_core
    lib_linux_libc_oak --> linux_loader