---
title: Module Dependency Graph
---
flowchart LR
    lib_Linux_oak(["Linux.oak"])
    subgraph stdlib_linux ["linux"]
        linux_constants("linux-constants")
        linux_libc("linux-libc")
        linux_windowing("linux-windowing")
        linux_core("linux-core")
        linux_loader("linux-loader")
    end
    subgraph stdlib_core ["Standard Library"]
        writes("writes")
        std("std")
        sys("sys")
    end
    linux_libc --> sys
    linux_libc --> writes
    linux_libc --> linux_constants
    linux_libc --> linux_core
    linux_libc --> linux_loader
    linux_windowing --> sys
    linux_windowing --> writes
    linux_windowing --> linux_constants
    linux_windowing --> linux_core
    linux_windowing --> linux_loader
    linux_core --> sys
    linux_core --> linux_constants
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    lib_Linux_oak --> sys
    lib_Linux_oak --> writes
    lib_Linux_oak --> linux_constants
    lib_Linux_oak --> linux_core
    lib_Linux_oak --> linux_loader
    lib_Linux_oak --> linux_windowing
    lib_Linux_oak --> linux_libc
    sys --> std