---
title: Module Dependency Graph
---
flowchart LR
    lib_Linux_oak(["Linux.oak"])
    linux_loader("linux-loader")
    linux_windowing("linux-windowing")
    linux_libc("linux-libc")
    sys("sys")
    writes("writes")
    linux_constants("linux-constants")
    linux_core("linux-core")
    lib_Linux_oak --> sys
    lib_Linux_oak --> writes
    lib_Linux_oak --> linux_constants
    lib_Linux_oak --> linux_core
    lib_Linux_oak --> linux_loader
    lib_Linux_oak --> linux_windowing
    lib_Linux_oak --> linux_libc