---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_linux_fonts_oak(["linux-fonts.oak"])
        std["std"]
        writes["writes"]
        linux_core["linux-core"]
        sys["sys"]
        linux_constants["linux-constants"]
        linux_loader["linux-loader"]
    end
    lib_linux_fonts_oak --> sys
    lib_linux_fonts_oak --> writes
    lib_linux_fonts_oak --> linux_core
    lib_linux_fonts_oak --> linux_loader
    linux_core --> sys
    linux_core --> linux_constants
    sys --> std
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core