---
title: Module Dependency Graph
---
flowchart LR
    lib_linux_libc_oak(["linux-libc.oak"])
    subgraph stdlib_linux ["linux"]
        linux_constants("linux-constants")
        linux_core("linux-core")
        linux_loader("linux-loader")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        std("std")
        writes("writes")
    end
    linux_core --> sys
    linux_core --> linux_constants
    linux_loader --> sys
    linux_loader --> linux_constants
    linux_loader --> linux_core
    lib_linux_libc_oak --> sys
    lib_linux_libc_oak --> writes
    lib_linux_libc_oak --> linux_constants
    lib_linux_libc_oak --> linux_core
    lib_linux_libc_oak --> linux_loader
    sys --> std