---
title: Module Dependency Graph
---
flowchart LR
    lib_linux_loader_oak(["linux-loader.oak"])
    subgraph stdlib_linux ["linux"]
        linux_constants("linux-constants")
        linux_core("linux-core")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        std("std")
    end
    linux_core --> sys
    linux_core --> linux_constants
    lib_linux_loader_oak --> sys
    lib_linux_loader_oak --> linux_constants
    lib_linux_loader_oak --> linux_core
    sys --> std