---
title: Module Dependency Graph
---
flowchart LR
    lib_linux_windowing_oak(["linux-windowing.oak"])
    linux_loader("linux-loader")
    sys("sys")
    writes("writes")
    linux_constants("linux-constants")
    linux_core("linux-core")
    lib_linux_windowing_oak --> sys
    lib_linux_windowing_oak --> writes
    lib_linux_windowing_oak --> linux_constants
    lib_linux_windowing_oak --> linux_core
    lib_linux_windowing_oak --> linux_loader