---
title: Module Dependency Graph
---
flowchart LR
    lib_linux_core_oak(["linux-core.oak"])
    sys("sys")
    linux_constants("linux-constants")
    lib_linux_core_oak --> sys
    lib_linux_core_oak --> linux_constants