---
title: Module Dependency Graph
---
flowchart LR
    lib_math_stats_oak(["math-stats.oak"])
    thread --> std
    lib_math_stats_oak --> std
    lib_math_stats_oak --> sort
    lib_math_stats_oak --> math_base
    lib_math_stats_oak --> thread
    sort --> std
    sort --> thread
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        math_base("math-base")
        std("std")
        sort("sort")
    end