---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_math_stats_oak(["math-stats.oak"])
        sort["sort"]
        thread["thread"]
        std["std"]
        math_base["math-base"]
    end
    lib_math_stats_oak --> std
    lib_math_stats_oak --> sort
    lib_math_stats_oak --> math_base
    lib_math_stats_oak --> thread
    sort --> std
    sort --> thread
    thread --> std