---
title: Module Dependency Graph
---
flowchart LR
    lib_math_geo_oak(["math-geo.oak"])
    subgraph stdlib_core ["Standard Library"]
        math_base("math-base")
    end
    lib_math_geo_oak --> math_base