---
title: Module Dependency Graph
---
flowchart LR
    lib_math_oak(["math.oak"])
    math_base("math-base")
    math_geo("math-geo")
    math_stats("math-stats")
    lib_math_oak --> math_base
    lib_math_oak --> math_geo
    lib_math_oak --> math_stats