---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_math_geo_oak(["math-geo.oak"])
        math_base["math-base"]
    end
    lib_math_geo_oak --> math_base