---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        sort["sort"]
        thread["thread"]
        lib_math_oak(["math.oak"])
        math_base["math-base"]
        math_geo["math-geo"]
        math_stats["math-stats"]
    end
    sort --> std
    sort --> thread
    thread --> std
    lib_math_oak --> math_base
    lib_math_oak --> math_geo
    lib_math_oak --> math_stats
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread