---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        http["http"]
        json["json"]
        thread["thread"]
        sort["sort"]
        str["str"]
        fmt["fmt"]
        lib_md_oak(["md.oak"])
        std["std"]
        fs["fs"]
    end
    http --> std
    http --> str
    http --> fs
    http --> fmt
    http --> sort
    http --> json
    http --> thread
    json --> std
    json --> str
    thread --> std
    sort --> std
    sort --> thread
    str --> std
    fmt --> std
    lib_md_oak --> std
    lib_md_oak --> str
    lib_md_oak --> fmt
    lib_md_oak --> http
    fs --> thread