---
title: Module Dependency Graph
---
flowchart LR
    lib_md_oak(["md.oak"])
    subgraph stdlib_core ["Standard Library"]
        str("str")
        fs("fs")
        std("std")
        http("http")
        sort("sort")
        fmt("fmt")
        thread("thread")
        json("json")
    end
    str --> std
    http --> std
    http --> str
    http --> fs
    http --> fmt
    http --> sort
    http --> json
    http --> thread
    fs --> thread
    sort --> std
    sort --> thread
    fmt --> std
    lib_md_oak --> std
    lib_md_oak --> str
    lib_md_oak --> fmt
    lib_md_oak --> http
    thread --> std
    json --> std
    json --> str