---
title: Module Dependency Graph
---
flowchart LR
    lib_md_oak(["md.oak"])
    fmt("fmt")
    http("http")
    std("std")
    str("str")
    lib_md_oak --> std
    lib_md_oak --> str
    lib_md_oak --> fmt
    lib_md_oak --> http