---
title: Module Dependency Graph
---
flowchart LR
    lib_mermaid_oak(["mermaid.oak"])
    subgraph stdlib_core ["Standard Library"]
        path("path")
        std("std")
        str("str")
        fmt("fmt")
        fs("fs")
        thread("thread")
    end
    lib_mermaid_oak --> std
    lib_mermaid_oak --> str
    lib_mermaid_oak --> fmt
    lib_mermaid_oak --> fs
    lib_mermaid_oak --> path
    str --> std
    fmt --> std
    fs --> thread
    thread --> std
    path --> std
    path --> str