---
title: Module Dependency Graph
---
flowchart LR
    lib_mermaid_oak(["mermaid.oak"])
    fs --> thread
    thread --> std
    path --> std
    path --> str
    lib_mermaid_oak --> std
    lib_mermaid_oak --> str
    lib_mermaid_oak --> fmt
    lib_mermaid_oak --> fs
    lib_mermaid_oak --> path
    str --> std
    fmt --> std
    subgraph stdlib_core ["Standard Library"]
        str("str")
        fmt("fmt")
        fs("fs")
        thread("thread")
        path("path")
        std("std")
    end