---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        path["path"]
        lib_mermaid_oak(["mermaid.oak"])
        str["str"]
        std["std"]
        fmt["fmt"]
        fs["fs"]
    end
    thread --> std
    path --> std
    path --> str
    lib_mermaid_oak --> std
    lib_mermaid_oak --> str
    lib_mermaid_oak --> fmt
    lib_mermaid_oak --> fs
    lib_mermaid_oak --> path
    str --> std
    fmt --> std
    fs --> thread