---
title: Module Dependency Graph
---
flowchart LR
    lib_msgpack_oak(["msgpack.oak"])
    std("std")
    str("str")
    thread("thread")
    lib_msgpack_oak --> std
    lib_msgpack_oak --> str
    lib_msgpack_oak --> thread