---
title: Module Dependency Graph
---
flowchart LR
    lib_msgpack_oak(["msgpack.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
    end
    thread --> std
    lib_msgpack_oak --> std
    lib_msgpack_oak --> str
    lib_msgpack_oak --> thread
    str --> std