---
title: Module Dependency Graph
---
flowchart LR
    lib_p2p_oak(["p2p.oak"])
    std("std")
    str("str")
    thread("thread")
    json("json")
    websocket("websocket")
    lib_p2p_oak --> std
    lib_p2p_oak --> str
    lib_p2p_oak --> thread
    lib_p2p_oak --> json
    lib_p2p_oak --> websocket