---
title: Module Dependency Graph
---
flowchart LR
    lib_pack_utils_oak(["pack-utils.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        json("json")
    end
    lib_pack_utils_oak --> std
    lib_pack_utils_oak --> str
    lib_pack_utils_oak --> json
    str --> std
    json --> std
    json --> str