---
title: Module Dependency Graph
---
flowchart LR
    lib_pack_oak(["pack.oak"])
    subgraph stdlib_Virtual ["Virtual"]
        Virtual("Virtual")
        Virtual_Bytecode("Virtual-Bytecode")
    end
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math("math")
        math_geo("math-geo")
        math_stats("math-stats")
    end
    subgraph stdlib_syntax ["syntax"]
        syntax_parse("syntax-parse")
        syntax_tokenize("syntax-tokenize")
        syntax_print("syntax-print")
        syntax("syntax")
        syntax_macros("syntax-macros")
    end
    subgraph stdlib_core ["Standard Library"]
        transpile("transpile")
        std("std")
        pack_utils("pack-utils")
        sort("sort")
        wasm_vm("wasm-vm")
        fs("fs")
        str("str")
        ast_transform("ast-transform")
        shell("shell")
        thread("thread")
        json("json")
        fmt("fmt")
        path("path")
    end
    thread --> std
    lib_pack_oak --> std
    lib_pack_oak --> fmt
    lib_pack_oak --> fs
    lib_pack_oak --> str
    lib_pack_oak --> path
    lib_pack_oak --> Virtual
    lib_pack_oak --> shell
    lib_pack_oak --> pack_utils
    lib_pack_oak --> transpile
    pack_utils --> std
    pack_utils --> str
    pack_utils --> json
    sort --> std
    sort --> thread
    Virtual --> std
    Virtual --> syntax
    Virtual --> str
    Virtual --> fmt
    Virtual --> fs
    Virtual --> Virtual_Bytecode
    json --> std
    json --> str
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    fmt --> std
    transpile --> std
    transpile --> fmt
    transpile --> ast_transform
    fs --> thread
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    Virtual_Bytecode --> std
    Virtual_Bytecode --> syntax
    Virtual_Bytecode --> wasm_vm
    Virtual_Bytecode --> fmt
    Virtual_Bytecode --> str
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    path --> std
    path --> str
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    math --> math_base
    math --> math_geo
    math --> math_stats
    str --> std
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    ast_transform --> std
    syntax_macros --> std
    syntax_macros --> syntax_parse
    shell --> std
    shell --> str
    shell --> fmt
    shell --> path
    shell --> fs