---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        math_base["math-base"]
        wasm_vm["wasm-vm"]
        Virtual["Virtual"]
        pack_utils["pack-utils"]
        syntax_parse["syntax-parse"]
        syntax_macros["syntax-macros"]
        math_geo["math-geo"]
        msgpack["msgpack"]
        std["std"]
        str["str"]
        sort["sort"]
        fmt["fmt"]
        ast_transform["ast-transform"]
        math["math"]
        syntax_print["syntax-print"]
        path["path"]
        transpile["transpile"]
        shell["shell"]
        math_stats["math-stats"]
        lib_pack_oak(["pack.oak"])
        Virtual_Bytecode["Virtual-Bytecode"]
        syntax_tokenize["syntax-tokenize"]
        fs["fs"]
        syntax["syntax"]
        thread["thread"]
    end
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    Virtual --> std
    Virtual --> syntax
    Virtual --> str
    Virtual --> fmt
    Virtual --> path
    Virtual --> fs
    Virtual --> Virtual_Bytecode
    pack_utils --> std
    pack_utils --> str
    pack_utils --> msgpack
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    syntax_macros --> std
    syntax_macros --> syntax_parse
    math_geo --> math_base
    msgpack --> std
    msgpack --> str
    msgpack --> thread
    str --> std
    sort --> std
    sort --> thread
    fmt --> std
    ast_transform --> std
    math --> math_base
    math --> math_geo
    math --> math_stats
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    path --> std
    path --> str
    transpile --> std
    transpile --> fmt
    transpile --> ast_transform
    shell --> std
    shell --> str
    shell --> fmt
    shell --> path
    shell --> fs
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    lib_pack_oak --> std
    lib_pack_oak --> fmt
    lib_pack_oak --> fs
    lib_pack_oak --> str
    lib_pack_oak --> path
    lib_pack_oak --> Virtual
    lib_pack_oak --> shell
    lib_pack_oak --> pack_utils
    lib_pack_oak --> transpile
    Virtual_Bytecode --> std
    Virtual_Bytecode --> syntax
    Virtual_Bytecode --> wasm_vm
    Virtual_Bytecode --> fmt
    Virtual_Bytecode --> str
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    fs --> thread
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    thread --> std