---
title: Module Dependency Graph
---
flowchart LR
    lib_pack_utils_oak(["pack-utils.oak"])
    std("std")
    str("str")
    json("json")
    lib_pack_utils_oak --> std
    lib_pack_utils_oak --> str
    lib_pack_utils_oak --> json