---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        std["std"]
        socket["socket"]
        lib_pop_oak(["pop.oak"])
        str["str"]
    end
    thread --> std
    lib_pop_oak --> std
    lib_pop_oak --> str
    lib_pop_oak --> thread
    lib_pop_oak --> socket
    str --> std