---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        wasm_vm_runtime["wasm-vm-runtime"]
        lib_runtime_codegen_oak(["runtime-codegen.oak"])
        runtime_native["runtime-native"]
        runtime_js["runtime-js"]
        wasm_vm["wasm-vm"]
        std["std"]
        str["str"]
        fmt["fmt"]
    end
    wasm_vm_runtime --> std
    wasm_vm_runtime --> str
    wasm_vm_runtime --> fmt
    lib_runtime_codegen_oak --> runtime_native
    lib_runtime_codegen_oak --> runtime_js
    lib_runtime_codegen_oak --> wasm_vm
    lib_runtime_codegen_oak --> wasm_vm_runtime
    lib_runtime_codegen_oak --> std
    lib_runtime_codegen_oak --> str
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    str --> std
    fmt --> std