---
title: Module Dependency Graph
---
flowchart LR
    lib_shell_oak(["shell.oak"])
    subgraph stdlib_core ["Standard Library"]
        thread("thread")
        std("std")
        str("str")
        fmt("fmt")
        path("path")
        fs("fs")
    end
    thread --> std
    lib_shell_oak --> std
    lib_shell_oak --> str
    lib_shell_oak --> fmt
    lib_shell_oak --> path
    lib_shell_oak --> fs
    str --> std
    fmt --> std
    path --> std
    path --> str
    fs --> thread