---
title: Module Dependency Graph
---
flowchart LR
    lib_shell_oak(["shell.oak"])
    str("str")
    fmt("fmt")
    path("path")
    fs("fs")
    std("std")
    lib_shell_oak --> std
    lib_shell_oak --> str
    lib_shell_oak --> fmt
    lib_shell_oak --> path
    lib_shell_oak --> fs