---
title: Module Dependency Graph
---
flowchart LR
    lib_smtp_oak(["smtp.oak"])
    socket("socket")
    std("std")
    str("str")
    thread("thread")
    lib_smtp_oak --> std
    lib_smtp_oak --> str
    lib_smtp_oak --> thread
    lib_smtp_oak --> socket