---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_smtp_oak(["smtp.oak"])
        std["std"]
        str["str"]
        thread["thread"]
        socket["socket"]
    end
    lib_smtp_oak --> std
    lib_smtp_oak --> str
    lib_smtp_oak --> thread
    lib_smtp_oak --> socket
    str --> std
    thread --> std