---
title: Module Dependency Graph
---
flowchart LR
    lib_sort_oak(["sort.oak"])
    subgraph stdlib_core ["Standard Library"]
        std("std")
        thread("thread")
    end
    thread --> std
    lib_sort_oak --> std
    lib_sort_oak --> thread