---
title: Module Dependency Graph
---
flowchart LR
    lib_syntax_macros_oak(["syntax-macros.oak"])
    subgraph stdlib_syntax ["syntax"]
        syntax_parse("syntax-parse")
        syntax_tokenize("syntax-tokenize")
    end
    subgraph stdlib_core ["Standard Library"]
        str("str")
        fmt("fmt")
        std("std")
    end
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    str --> std
    fmt --> std
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    lib_syntax_macros_oak --> std
    lib_syntax_macros_oak --> syntax_parse