---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        thread["thread"]
        lib_syntax_oak(["syntax.oak"])
        syntax_parse["syntax-parse"]
        str["str"]
        math_stats["math-stats"]
        std["std"]
        math["math"]
        fmt["fmt"]
        syntax_macros["syntax-macros"]
        syntax_print["syntax-print"]
        math_geo["math-geo"]
        sort["sort"]
        syntax_tokenize["syntax-tokenize"]
        math_base["math-base"]
    end
    thread --> std
    lib_syntax_oak --> syntax_tokenize
    lib_syntax_oak --> syntax_parse
    lib_syntax_oak --> syntax_macros
    lib_syntax_oak --> syntax_print
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    str --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    math --> math_base
    math --> math_geo
    math --> math_stats
    fmt --> std
    syntax_macros --> std
    syntax_macros --> syntax_parse
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    math_geo --> math_base
    sort --> std
    sort --> thread
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt