---
title: Module Dependency Graph
---
flowchart LR
    lib_syntax_tokenize_oak(["syntax-tokenize.oak"])
    lib_syntax_tokenize_oak --> std
    lib_syntax_tokenize_oak --> str
    lib_syntax_tokenize_oak --> fmt
    str --> std
    fmt --> std
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        fmt("fmt")
    end