---
title: Module Dependency Graph
---
flowchart LR
    lib_syntax_tokenize_oak(["syntax-tokenize.oak"])
    std("std")
    str("str")
    fmt("fmt")
    lib_syntax_tokenize_oak --> std
    lib_syntax_tokenize_oak --> str
    lib_syntax_tokenize_oak --> fmt