---
title: Module Dependency Graph
---
flowchart LR
    lib_syntax_parse_oak(["syntax-parse.oak"])
    subgraph stdlib_core ["Standard Library"]
        fmt("fmt")
        syntax_tokenize("syntax-tokenize")
        std("std")
        str("str")
    end
    fmt --> std
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    lib_syntax_parse_oak --> std
    lib_syntax_parse_oak --> str
    lib_syntax_parse_oak --> fmt
    lib_syntax_parse_oak --> syntax_tokenize
    str --> std