---
title: Module Dependency Graph
---
flowchart LR
    lib_syntax_oak(["syntax.oak"])
    subgraph stdlib_syntax ["syntax"]
        syntax_macros("syntax-macros")
        syntax_parse("syntax-parse")
        syntax_print("syntax-print")
        syntax_tokenize("syntax-tokenize")
    end
    subgraph stdlib_math ["math"]
        math_geo("math-geo")
        math_stats("math-stats")
        math("math")
        math_base("math-base")
    end
    subgraph stdlib_core ["Standard Library"]
        std("std")
        str("str")
        thread("thread")
        sort("sort")
        fmt("fmt")
    end
    lib_syntax_oak --> syntax_tokenize
    lib_syntax_oak --> syntax_parse
    lib_syntax_oak --> syntax_macros
    lib_syntax_oak --> syntax_print
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    str --> std
    syntax_macros --> std
    syntax_macros --> syntax_parse
    math --> math_base
    math --> math_geo
    math --> math_stats
    thread --> std
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    sort --> std
    sort --> thread
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    fmt --> std