---
title: Module Dependency Graph
---
flowchart LR
    lib_syntax_macros_oak(["syntax-macros.oak"])
    std("std")
    syntax_parse("syntax-parse")
    lib_syntax_macros_oak --> std
    lib_syntax_macros_oak --> syntax_parse