---
title: Module Dependency Graph
---
flowchart LR
    lib_syntaxfmt_oak(["syntaxfmt.oak"])
    subgraph stdlib_syntax ["syntax"]
        syntax_parse("syntax-parse")
        syntax_macros("syntax-macros")
        syntax_tokenize("syntax-tokenize")
        syntax("syntax")
        syntax_print("syntax-print")
    end
    subgraph stdlib_math ["math"]
        math_stats("math-stats")
        math("math")
        math_base("math-base")
        math_geo("math-geo")
    end
    subgraph stdlib_core ["Standard Library"]
        fs("fs")
        sort("sort")
        str("str")
        thread("thread")
        fmt("fmt")
        std("std")
    end
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    syntax_macros --> std
    syntax_macros --> syntax_parse
    fs --> thread
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    math --> math_base
    math --> math_geo
    math --> math_stats
    sort --> std
    sort --> thread
    lib_syntaxfmt_oak --> std
    lib_syntaxfmt_oak --> str
    lib_syntaxfmt_oak --> fs
    lib_syntaxfmt_oak --> syntax
    str --> std
    fmt --> std
    thread --> std
    math_geo --> math_base