---
title: Module Dependency Graph
---
flowchart LR
    lib_test_oak(["test.oak"])
    subgraph stdlib_math ["math"]
        math("math")
        math_base("math-base")
        math_geo("math-geo")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        fmt("fmt")
        debug("debug")
        sort("sort")
        thread("thread")
        std("std")
        str("str")
    end
    thread --> std
    str --> std
    math --> math_base
    math --> math_geo
    math --> math_stats
    lib_test_oak --> std
    lib_test_oak --> str
    lib_test_oak --> fmt
    lib_test_oak --> debug
    fmt --> std
    debug --> std
    debug --> str
    debug --> math
    debug --> sort
    debug --> fmt
    sort --> std
    sort --> thread
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread