---
title: Module Dependency Graph
---
flowchart LR
    lib_test_oak(["test.oak"])
    subgraph stdlib_math ["math"]
        math_base("math-base")
        math_geo("math-geo")
        math_stats("math-stats")
        math("math")
    end
    subgraph stdlib_core ["Standard Library"]
        sort("sort")
        thread("thread")
        fmt("fmt")
        std("std")
        str("str")
        debug("debug")
    end
    debug --> std
    debug --> str
    debug --> math
    debug --> sort
    debug --> fmt
    sort --> std
    sort --> thread
    thread --> std
    fmt --> std
    math_geo --> math_base
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    lib_test_oak --> std
    lib_test_oak --> str
    lib_test_oak --> fmt
    lib_test_oak --> debug
    str --> std
    math --> math_base
    math --> math_geo
    math --> math_stats