---
title: Module Dependency Graph
---
flowchart LR
    lib_test_oak(["test.oak"])
    std("std")
    str("str")
    fmt("fmt")
    debug("debug")
    lib_test_oak --> std
    lib_test_oak --> str
    lib_test_oak --> fmt
    lib_test_oak --> debug