---
title: Module Dependency Graph
---
flowchart LR
    lib_transpile_oak(["transpile.oak"])
    subgraph stdlib_core ["Standard Library"]
        ast_transform("ast-transform")
        std("std")
        fmt("fmt")
    end
    ast_transform --> std
    lib_transpile_oak --> std
    lib_transpile_oak --> fmt
    lib_transpile_oak --> ast_transform
    fmt --> std