---
title: Module Dependency Graph
---
flowchart LR
    lib_transpile_oak(["transpile.oak"])
    std("std")
    fmt("fmt")
    ast_transform("ast-transform")
    lib_transpile_oak --> std
    lib_transpile_oak --> fmt
    lib_transpile_oak --> ast_transform