---
title: Module Dependency Graph
---
flowchart LR
    lib_transpile_oak(["transpile.oak"])
    ast_transform --> std
    lib_transpile_oak --> std
    lib_transpile_oak --> fmt
    lib_transpile_oak --> ast_transform
    fmt --> std
    subgraph stdlib_core ["Standard Library"]
        fmt("fmt")
        ast_transform("ast-transform")
        std("std")
    end