---
title: Module Dependency Graph
---
flowchart LR
    lib_video_oak(["video.oak"])
    thread("thread")
    std("std")
    math("math")
    lib_video_oak --> std
    lib_video_oak --> math
    lib_video_oak --> thread