---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        std["std"]
        lib_VirtualToken_oak(["VirtualToken.oak"])
    end
    lib_VirtualToken_oak --> std