---
title: Module Dependency Graph
---
flowchart LR
    lib_Virtual_oak(["Virtual.oak"])
    subgraph stdlib_syntax ["syntax"]
        syntax_tokenize("syntax-tokenize")
        syntax_parse("syntax-parse")
        syntax_macros("syntax-macros")
        syntax_print("syntax-print")
        syntax("syntax")
    end
    subgraph stdlib_math ["math"]
        math("math")
        math_geo("math-geo")
        math_base("math-base")
        math_stats("math-stats")
    end
    subgraph stdlib_core ["Standard Library"]
        sort("sort")
        fs("fs")
        Virtual_Bytecode("Virtual-Bytecode")
        wasm_vm("wasm-vm")
        str("str")
        thread("thread")
        std("std")
        fmt("fmt")
    end
    lib_Virtual_oak --> std
    lib_Virtual_oak --> syntax
    lib_Virtual_oak --> str
    lib_Virtual_oak --> fmt
    lib_Virtual_oak --> fs
    lib_Virtual_oak --> Virtual_Bytecode
    math --> math_base
    math --> math_geo
    math --> math_stats
    str --> std
    fs --> thread
    Virtual_Bytecode --> std
    Virtual_Bytecode --> syntax
    Virtual_Bytecode --> wasm_vm
    Virtual_Bytecode --> fmt
    Virtual_Bytecode --> str
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    syntax_macros --> std
    syntax_macros --> syntax_parse
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    math_geo --> math_base
    thread --> std
    fmt --> std
    sort --> std
    sort --> thread
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread