---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        syntax_parse["syntax-parse"]
        syntax_macros["syntax-macros"]
        fmt["fmt"]
        syntax_tokenize["syntax-tokenize"]
        str["str"]
        math["math"]
        math_base["math-base"]
        syntax_print["syntax-print"]
        thread["thread"]
        math_stats["math-stats"]
        std["std"]
        sort["sort"]
        lib_Virtual_Bytecode_oak(["Virtual-Bytecode.oak"])
        wasm_vm["wasm-vm"]
        math_geo["math-geo"]
        syntax["syntax"]
    end
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    syntax_macros --> std
    syntax_macros --> syntax_parse
    fmt --> std
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    str --> std
    math --> math_base
    math --> math_geo
    math --> math_stats
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    thread --> std
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    sort --> std
    sort --> thread
    lib_Virtual_Bytecode_oak --> std
    lib_Virtual_Bytecode_oak --> syntax
    lib_Virtual_Bytecode_oak --> wasm_vm
    lib_Virtual_Bytecode_oak --> fmt
    lib_Virtual_Bytecode_oak --> str
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    math_geo --> math_base
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print