---
title: Module Dependency Graph
---
flowchart LR
    lib_Virtual_Bytecode_oak(["Virtual-Bytecode.oak"])
    str("str")
    std("std")
    syntax("syntax")
    wasm_vm("wasm-vm")
    fmt("fmt")
    lib_Virtual_Bytecode_oak --> std
    lib_Virtual_Bytecode_oak --> syntax
    lib_Virtual_Bytecode_oak --> wasm_vm
    lib_Virtual_Bytecode_oak --> fmt
    lib_Virtual_Bytecode_oak --> str