---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        math["math"]
        str["str"]
        syntax_tokenize["syntax-tokenize"]
        syntax_macros["syntax-macros"]
        syntax_parse["syntax-parse"]
        Virtual_Bytecode["Virtual-Bytecode"]
        thread["thread"]
        sort["sort"]
        path["path"]
        std["std"]
        wasm_vm["wasm-vm"]
        lib_Virtual_oak(["Virtual.oak"])
        syntax_print["syntax-print"]
        fmt["fmt"]
        math_base["math-base"]
        math_geo["math-geo"]
        syntax["syntax"]
        math_stats["math-stats"]
        fs["fs"]
    end
    math --> math_base
    math --> math_geo
    math --> math_stats
    str --> std
    syntax_tokenize --> std
    syntax_tokenize --> str
    syntax_tokenize --> fmt
    syntax_macros --> std
    syntax_macros --> syntax_parse
    syntax_parse --> std
    syntax_parse --> str
    syntax_parse --> fmt
    syntax_parse --> syntax_tokenize
    Virtual_Bytecode --> std
    Virtual_Bytecode --> syntax
    Virtual_Bytecode --> wasm_vm
    Virtual_Bytecode --> fmt
    Virtual_Bytecode --> str
    thread --> std
    sort --> std
    sort --> thread
    path --> std
    path --> str
    wasm_vm --> std
    wasm_vm --> str
    wasm_vm --> fmt
    lib_Virtual_oak --> std
    lib_Virtual_oak --> syntax
    lib_Virtual_oak --> str
    lib_Virtual_oak --> fmt
    lib_Virtual_oak --> path
    lib_Virtual_oak --> fs
    lib_Virtual_oak --> Virtual_Bytecode
    syntax_print --> std
    syntax_print --> str
    syntax_print --> math
    syntax_print --> fmt
    syntax_print --> syntax_tokenize
    fmt --> std
    math_geo --> math_base
    syntax --> syntax_tokenize
    syntax --> syntax_parse
    syntax --> syntax_macros
    syntax --> syntax_print
    math_stats --> std
    math_stats --> sort
    math_stats --> math_base
    math_stats --> thread
    fs --> thread