---
title: Module Dependency Graph
---
flowchart LR
    lib_wasm_vm_oak(["wasm-vm.oak"])
    str("str")
    fmt("fmt")
    std("std")
    lib_wasm_vm_oak --> std
    lib_wasm_vm_oak --> str
    lib_wasm_vm_oak --> fmt