---
title: Module Dependency Graph
---
flowchart LR
    lib_wasm_vm_runtime_oak(["wasm-vm-runtime.oak"])
    std("std")
    str("str")
    fmt("fmt")
    lib_wasm_vm_runtime_oak --> std
    lib_wasm_vm_runtime_oak --> str
    lib_wasm_vm_runtime_oak --> fmt