---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_web_fetch_oak(["web-fetch.oak"])
        web_runtime["web-runtime"]
    end
    lib_web_fetch_oak --> web_runtime