---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        windows_loader["windows-loader"]
        windows_gdi["windows-gdi"]
        windows_flags["windows-flags"]
        windows_core["windows-core"]
        std["std"]
        windows_constants["windows-constants"]
        lib_win_common_oak(["win-common.oak"])
        windows["windows"]
        windows_registry["windows-registry"]
        windows_windowing["windows-windowing"]
        sys["sys"]
        writes["writes"]
        windows_net["windows-net"]
        windows_kernel["windows-kernel"]
    end
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants
    windows_core --> sys
    windows_core --> windows_constants
    lib_win_common_oak --> windows
    windows --> sys
    windows --> writes
    windows --> windows_constants
    windows --> windows_flags
    windows --> windows_registry
    windows --> windows_net
    windows --> windows_windowing
    windows --> windows_gdi
    windows --> windows_kernel
    windows --> windows_loader
    windows --> windows_core
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    sys --> std
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags