---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_kernel_oak(["windows-kernel.oak"])
    sys("sys")
    writes("writes")
    windows_constants("windows-constants")
    windows_flags("windows-flags")
    lib_windows_kernel_oak --> sys
    lib_windows_kernel_oak --> writes
    lib_windows_kernel_oak --> windows_constants
    lib_windows_kernel_oak --> windows_flags