---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_windowing_oak(["windows-windowing.oak"])
    lib_windows_windowing_oak --> sys
    lib_windows_windowing_oak --> writes
    lib_windows_windowing_oak --> windows_constants
    lib_windows_windowing_oak --> windows_flags
    lib_windows_windowing_oak --> std
    sys --> std
    subgraph stdlib_windows ["windows"]
        windows_constants("windows-constants")
        windows_flags("windows-flags")
    end
    subgraph stdlib_core ["Standard Library"]
        writes("writes")
        sys("sys")
        std("std")
    end