---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_oak(["windows.oak"])
    subgraph stdlib_windows ["windows"]
        windows_kernel("windows-kernel")
        windows_core("windows-core")
        windows_registry("windows-registry")
        windows_windowing("windows-windowing")
        windows_constants("windows-constants")
        windows_net("windows-net")
        windows_flags("windows-flags")
        windows_loader("windows-loader")
        windows_gdi("windows-gdi")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        writes("writes")
        std("std")
    end
    windows_kernel --> sys
    windows_kernel --> writes
    windows_kernel --> windows_constants
    windows_kernel --> windows_flags
    windows_core --> sys
    windows_core --> windows_constants
    windows_registry --> sys
    windows_registry --> writes
    windows_registry --> windows_constants
    windows_registry --> windows_flags
    windows_windowing --> sys
    windows_windowing --> writes
    windows_windowing --> windows_constants
    windows_windowing --> windows_flags
    windows_windowing --> std
    sys --> std
    windows_net --> sys
    windows_net --> writes
    windows_net --> windows_constants
    windows_net --> windows_flags
    lib_windows_oak --> sys
    lib_windows_oak --> writes
    lib_windows_oak --> windows_constants
    lib_windows_oak --> windows_flags
    lib_windows_oak --> windows_registry
    lib_windows_oak --> windows_net
    lib_windows_oak --> windows_windowing
    lib_windows_oak --> windows_gdi
    lib_windows_oak --> windows_kernel
    lib_windows_oak --> windows_loader
    lib_windows_oak --> windows_core
    windows_loader --> sys
    windows_loader --> windows_constants
    windows_loader --> windows_kernel
    windows_gdi --> sys
    windows_gdi --> writes
    windows_gdi --> windows_constants