---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_net_oak(["windows-net.oak"])
    subgraph stdlib_windows ["windows"]
        windows_constants("windows-constants")
        windows_flags("windows-flags")
    end
    subgraph stdlib_core ["Standard Library"]
        writes("writes")
        sys("sys")
        std("std")
    end
    lib_windows_net_oak --> sys
    lib_windows_net_oak --> writes
    lib_windows_net_oak --> windows_constants
    lib_windows_net_oak --> windows_flags
    sys --> std