---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_loader_oak(["windows-loader.oak"])
    sys("sys")
    windows_constants("windows-constants")
    windows_kernel("windows-kernel")
    lib_windows_loader_oak --> sys
    lib_windows_loader_oak --> windows_constants
    lib_windows_loader_oak --> windows_kernel