---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_core_oak(["windows-core.oak"])
    sys("sys")
    windows_constants("windows-constants")
    lib_windows_core_oak --> sys
    lib_windows_core_oak --> windows_constants