---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_fonts_oak(["windows-fonts.oak"])
    sys --> std
    lib_windows_fonts_oak --> sys
    lib_windows_fonts_oak --> writes
    lib_windows_fonts_oak --> windows_constants
    subgraph stdlib_core ["Standard Library"]
        windows_constants("windows-constants")
        sys("sys")
        std("std")
        writes("writes")
    end