---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        lib_windows_gdi_oak(["windows-gdi.oak"])
        sys["sys"]
        std["std"]
        writes["writes"]
        windows_constants["windows-constants"]
    end
    lib_windows_gdi_oak --> sys
    lib_windows_gdi_oak --> writes
    lib_windows_gdi_oak --> windows_constants
    sys --> std