---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_kernel_oak(["windows-kernel.oak"])
    subgraph stdlib_windows ["windows"]
        windows_constants("windows-constants")
        windows_flags("windows-flags")
    end
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        std("std")
        writes("writes")
    end
    lib_windows_kernel_oak --> sys
    lib_windows_kernel_oak --> writes
    lib_windows_kernel_oak --> windows_constants
    lib_windows_kernel_oak --> windows_flags
    sys --> std