---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_registry_oak(["windows-registry.oak"])
    windows_flags("windows-flags")
    sys("sys")
    writes("writes")
    windows_constants("windows-constants")
    lib_windows_registry_oak --> sys
    lib_windows_registry_oak --> writes
    lib_windows_registry_oak --> windows_constants
    lib_windows_registry_oak --> windows_flags