---
title: Module Dependency Graph
---
flowchart LR
    lib_windows_gdi_oak(["windows-gdi.oak"])
    lib_windows_gdi_oak --> sys
    lib_windows_gdi_oak --> writes
    lib_windows_gdi_oak --> windows_constants
    sys --> std
    subgraph stdlib_core ["Standard Library"]
        sys("sys")
        std("std")
        writes("writes")
        windows_constants("windows-constants")
    end