---
title: Module Dependency Graph
---
flowchart LR
    subgraph project_modules ["Project Modules"]
        json["json"]
        socket["socket"]
        lib_WLAN_oak(["WLAN.oak"])
        str["str"]
        std["std"]
        thread["thread"]
    end
    json --> std
    json --> str
    lib_WLAN_oak --> std
    lib_WLAN_oak --> str
    lib_WLAN_oak --> thread
    lib_WLAN_oak --> json
    lib_WLAN_oak --> socket
    str --> std
    thread --> std